import random

def Style():
    styles = [
        "Edgard Allan Poe",
        "Oscar Wilde",
        "J.R.R. Tolkien",
        "George R. R. Martin",
        "Terry Pratchett",
        "Neil Gaiman",
        "Patrick Rothfuss",
        "Ursula K. Le Guin",
        "Stephen King",
        "H. P. Lovecraft",
        "Isaac Asimov",
        "Bram Stoker",
        "Erin Morgenstern",
        "Madeline Miller",
        "Phillip Pullman",
        "F. Scott Fitzgerald",
        "Mark Twain",
        "George Orwell",
        "Fyodor Dostoevsky",
        "Mary Shelley",
        "Lord Byron",
        "William Shakespeare",
        "Fran Kafka",
        "C.S. Lewis",
        "Jorge Luis Borges",
        "Hermann Hesse",
        "Richard Bach",
        "Haruki Murakami",
        "Maya Angelou",
        "Gabriel García Márquez", 
        "Jane Austen",
        "Chinua Achebe",
        "Virginia Woolf",
        "Salman Rushdie",
        "Toni Morrison",
        "Monty Pythons",
        "Ernest Hemingway",
        "Homer",
        "Dante Alighieri"
        
        ]
    return random.choice(styles)
