'''

Inspiration:
	- Birds (meaning)
	Beid (m,f)  Theemin (f,m)  Zibal (m)
	Adler (m)  Aetius (m)  Aghavni (f)  Ainara (f)  Alcyone (f)  Alondra (f)  Ane 2 (m)  Anne 2 (m)  Aquila (m,f)  Aras (m)  Ari 2 (m)  Arke 2 (m)  Arne 1 (m)  Arūnas (m)  Astor (m)  Awilix (f)  Bibigul (f)  Brân (m)  Bran 1 (m)  Brennus (m)  Çağrı (m,f)  Cauã (m)  Circe (f)  Colum (m)  Columba (m,f)  Corbin (m)  Csongor (m)  Diindiisi (f,m)  Dove (f)  Dror (m)  Enara (f)  Falk (m)  Fiachna (m)  Halcyon (f)  Hraban (m)  Hrafn (m)  Jemima (f)  Jeruti (f)  Jonah (m)  Kestrel (f)  Korbinian (m)  Koronis (f)  Lærke (f)  Lagle (f)  Lark (f)  Linnet (f)  Llinos (f)  Mayur (m)  Merel (f)  Merle (f,m)  Nauja (f)  Paloma (f)  Parastoo (f)  Pëllumb (m)  Petrit (m)  Philomel (f)  Phineus (m)  Raven (f,m)  Roan (m)  Robin (m,f)  Rocco (m)  Şahin (m)  Sarika (f)  Shahin (m)  Shqipe (f)  Sinikka (f)  Sokol (m)  Sona 2 (f)  Sparrow (m,f)  Suna (f)  Suzume (f)  Sycorax (f)  Tahlako (m)  Tiiu (f)  Tinúviel (f)  Toiba (f)  Toygar (m)  Tsubame (f)  Tsuru (f)  Tulugaq (m,f)  Turgay (m)  Tzufit (f)  Urpi (f)  Usoa (f)  Vasco (m)  Walela (f)  Waman (m)  Wambdi (m,f)  Wambli (m,f)  Wren (f)
	Aenoheso (m)  Ákos (m)  Andor 1 (m)  Ankarl (m)  Antiman (m)  Antinanco (m)  Aqissiaq (m)  Arnar (m)  Arnbjǫrg (f)  Arnfinn (m)  Arnfried (m)  Arnoald (m)  Arnold (m)  Arnsteinn (m)  Arnulf (m)  Arvid (m)  Aucaman (m)  Berahthraban (m)  Bertram (m)  Branwen (f)  Chizuru (f)  Crawford (m)  Cuauhtemoc (m)  Engilram (m)  Erdoğan (m)  Féchín (m)  Fiachra (m)  Fiachrae (m)  Guntram (m)  Gwalchmai (m)  Hayato (m)  Haytham (m)  Hong (m,f)  Hrafnhildr (f)  Hrambert (m)  Huitzilopochtli (m)  Isapo-Muxika (m)  Jacey (f,m)  Jaden (m,f)  Jalen (m)  Javion (m)  Javon (m)  Jaycee (f,m)  Jayla (f)  Jaylah (f)  Jaylee (f)  Jayleen (f)  Jaylene (f)  Jaylinn (f)  Jaylyn (f)  Jaylynn (f)  Lonán (m)  Mekaisto (m)  Mupitsukupʉ (m)  Pelias (m)  Pittiulaaq (f,m)  Qinnuajuaq (f,m)  Quetzalcoatl (m)  Quetzalli (f)  Svanhild (f)  Swanahildiz (f)  Swanhild (f)  Þórarinn (m)  Ugochi (f)  Ugochukwu (m)  Uthman (m)  Wawatam (m)  Wolfram (m)  Wrenlee (f)  Wrenley (f)  Xochiquetzal (f)
	Acuauh (m)  Adalram (m)  Aëdon (f)  Aénohe (m)  Aénȯhea'eotse (m)  Aénȯhéévé'hȧhtse (m)  Aénȯheméóná'e (f)  Aénȯhenéhovóhe (m)  Æringunnr (f)  Ærinví (f)  Ærngautr (m)  Águila (f)  Ahiru (f)  Aiah (m)  Aigssiarssuk (f)  Ainhara (f)  Ajah (m)  Akhom (m)  Aĸigsseĸ (f)  Aĸigssiaĸ (f)  Akitaka (m)  Akku (f)  Akleja (f)  Aktuygun (f)  Aladfar (f)  Alaram (m)  Alathfar (f)  Alauda (f)  Alfarinn (m)  Algorab (m)  Alik (f)  Alkhazur (m)  Alotte (f)  Alouetta (f)  Alouette (f)  Alsïnbikä (f)  Amke (f)  Ampúsh (m)  Amshel (m)  Andalib (f,m)  Andleeb (f)  Angilram (m)  Angir (m,f)  Angwusnasomtaqa (f)  Anzû (m)  Aoileann (f)  Aomi (f,m)  Aqissiarsuk (f)  Aqqoš (f)  Aqqw (m,f)  Aqsarlaq (f)  Aquetzalli (f,m)  Aquillius (m)  Arabert (m)  Aragund (f)  Aramund (m)  Ard (m)  Arda (f)  Ardin (m)  Ardziv (m)  Ardzvig (f)  Aregis (m)  Arendje (m,f)  Arhild (f)  Ariwald (m)  Arna (f)  Arnas (m)  Arnbert (m)  Arnbjörn (m)  Arnbrand (m)  Arnbrandr (m)  Arndís (f)  Arnevi (f)  Arnfastr (m)  Arnfrid (f)  Arnfríðr (f)  Arnfrøðr (m)  Arngeirr (m)  Arngerðr (f)  Arngrímr (m)  Arnheiðr (f)  Arnhildr (f)  Arnhǫfði (m)  Arnida (f)  Arnketill (m)  Arnlaug (f,m)  Arnlín (f)  Arnljótr (m)  Arnmóðr (m)  Arnmundr (m)  Arnniútr (m)  Arnrós (f)  Arnrún (f)  Arnþjófr (m)  Arnþrúðr (f)  Arnulfr (m)  Arnveig (f)  Arnwin (m)  Arny (f)  Artoyt (m,f)  Arulf (m)  Arvin (m)  Asfour (m)  Astore (m)  Atbir (m)  Átoko (m)  Atotoztli (f)  Atsa (f)  Ayah (m,f)  Aydoğan (f,m)  Azio (m)  Aztamitl (m)  Aztatl (m)  Aztlan (m,f)  Badb (f)  Bagala (f)  Bahrin (f)  Baige (f)  Bailu (f)  Balandis (m)  Balbala (f)  Baldram (m)  Banoy (m)  Banzou (m)  Baojuan (f)  Baoyan (f)  Bawan (m,f)  Baz (m)  Baze (m)  Bazê (f)  Beila (m)  Bennu (f)  Bihong (f)  Bilbil (m)  Biliram (m)  Biyan (f)  Blæingr (m)  Boduognatos (m)  Bozgul (f)  Brandubh (m)  Brangen (m)  Branoc (m)  Bugafer (f,m)  Bülbül (f)  Bulbul (m)  Bülbülcan (m)  Bulzhamuur (f)  Bumin (m)  Bürged (m)  Burgutoy (f)  Burkit (m)  Bürkitbay (m)  Cadhan (m)  Caley (f,m)  Caligo (m)  Cathan (m)  Cathubodua (f)  Çaukaş (m)  Cecuauh (m)  Celidonius (m)  Cetanwakuwa (m)  Čezek (f)  Chakak (f)  Chakavak (f)  Chamol (m)  Chamolmani (m)  Chamuk (f)  Chandrakin (f)  Changyan (f)  Chanjuan (f)  Chash-köök (m)  Chaurisse (f)  Chaytan (m)  Cheglok (m)  Chelidon (f)  Chelidonia (f)  Chelidonios (m)  Chenoa (f)  Chenying (f)  Chepchen (f)  Ches-kartiğa (m)  Chichatlapal (m)  Chiconcuauh (m)  Chilcanauh (m)  Chilina (f)  Chimalcuauhtli (m)  Chimalis (f)  Chizuko (f)  Chizuruko (f)  Chizzy (f)  Chӗkeş (f)  Chogan (m)  Chonon (f,m)  Chóro (m)  Chosovi (f)  Chovka (f)  Chrysopeleia (f)  Chunlu (f)  Chunyan (f,m)  Chunying (f,m)  Chuying (f)  Cirilla (f)  Cīrulis (m)  Cisne (f,m)  Cochcanauh (m,f)  Colas (m)  Condorito (m)  Corvus (m)  Corydon (m)  Cozcacuauh (m)  Cuauhatl (m)  Cuauhcoatl (m,f)  Cuauhcopil (m)  Cuauhicopi (m)  Cuauhihuitl (m)  Cuauhilama (m)  Cuauhnecahual (m)  Cuauhnenemi (m)  Cuauhpan (m)  Cuauhpopoca (m)  Cuauhquen (m,f)  Cuauhquiyahuacatl (m)  Cuauhtapalca (m)  Cuauhtecolotl (m)  Cuauhtecpan (m)  Cuauhtepotzo (m)  Cuauhtilma (m)  Cuauhtin (m)  Cuauhtlamati (m)  Cuauhtlapetz (f)  Cuauhtlapeuh (m)  Cuauhtlatoa (m)  Cuauhtlatoatzin (m)  Cuauhtlatzacuilotl (m)  Cuauhtlaxaya (m)  Cuauhtli (m,f)  Cuauhtlichimal (m)  Cuauhtopilli (m)  Cuauhtzitzimitl (m)  Cuauhtzontecon (m)  Cuauhxilotl (m,f)  Cuauhyollo (m)  Cuauhzton (m)  Cuco (m)  Cuichang (f)  Cuie (f)  Cuifen (f)  Cuili (f)  Cuiliang (f)  Cuiling (f)  Cuiluan (f)  Cuiming (f)  Cuiping (f)  Cuiquan (f)  Cuisheng (f)  Cuitao (f)  Cuixiang (f)  Cuixin (f)  Cuiyin (f)  Cuiying (f)  Cuiyuan (f)  Cuiyue (f)  Cuizhao (f)  Cygnet (f)  Cynfran (m)  Dalbaray (f)  Dallëndyshe (f)  Danying (f)  Decui (f)  Deepshikha (f)  Deyan (f)  Diaochan (f)  Dilbaz (f)  Dindrane (f)  Djeråd (m)  Djuråd (m)  Doğan (m)  Doli (f)  Dongyang (f)  Douwe (m)  Drossel (m)  Drudwen (f)  Dryops (m)  Dūja (f)  Dulcedram (m)  Dúna (f)  Durna (f)  Duva (f)  Dyveke (f)  Dzeguze (f)  Dzilna (f)  Éala (f)  Earngeat (m)  Earngith (f)  Earnsige (m)  Earnweald (m)  Earnwig (m)  Earnwine (m)  Earnwulf (m)  Edahna (f)  Eheder (m)  Ehrentraud (f)  Eitam (m)  Ēkara (f,m)  Elai (m)  Elaia (f)  Elang (m)  Elphir (m)  Elya (m)  Emmeram (m)  Enjirou (m)  Enkhtagtaa (m,f)  Enyan (f)  Enza (m)  Eos (f)  Erelis (m)  Erngeat (m)  Ernoul (m)  Erondina (f)  Fa'alupe (f,m)  Faílenn (f)  Fainche (f)  Fala (f)  Falco (m)  Falcon (m)  Falcona (f)  Falkny (f)  Falkon (m)  Fanfei (f)  Fangge (f)  Faoileán (m,f)  Feilin (f)  Feitang (f)  Fíacc (m)  Fiach (m)  Fiacha (m)  Fiech (m)  Finchley (f,m)  Folcram (m)  Fuhong (f)  Fumitaka (m)  Fuyan (f)  Fuying (f)  Gaagii (m)  Gac (m)  Gagara (m)  Gaku (m)  Galabin (m)  Galamb (f)  Galgan-nga (f)  Galka (m)  Garanwyn (m)  Gargabay (m)  Garrincha (m)  Garuda (m)  Gawen (m)  Gealbhán (m)  Gedia (m,f)  Geese (m)  Gelgéis (f)  Gerakina (f)  Gerana (f)  Gerle (f)  Gjeraqina (f)  Golubitsa (f)  Gorbat (m)  Gossamer (f)  Gruia (m)  Guanai (f)  Guangyan (f)  Guanhuan (f)  Guanmo (f)  Guanqiu (f)  Guanrui (f)  Guansu (f)  Guanwan (f)  Guanyan (f)  Guanyao (f)  Guanzhi (f)  Gulboz (f)  Gultovus (f)  Guluun (m)  Gurbaaz (m)  Gvantsa (f)  Gwain (m)  Gwalchgwyn (m)  Gwennol (f)  Gwylan (f)  Gyogurchun (f)  Haiuna (f)  Haiyan (f,m)  Haiying (f,m)  Hamsika (f)  Hansika (f)  Hansini (f)  Hansita (f)  Harapšeki (f)  Ḫarapšili (f)  Harpagon (m)  Hatoko (f)  Hatomi (f)  Hauk (m)  Haukr (m)  Hauksteinn (m)  Haukur (m)  Hawkeye (m,f)  Hayahito (m)  Hayaichirou (m)  Hayakazu (m)  Hayao (m)  Hayase (m)  Hayata (m)  Hayatarou (m)  Hayuma (m,f)  He'heēno (m)  He'heenóhká'e (f)  He'heenóhkéso (m)  Heilram (m)  Heimram (m)  Hejia (f,m)  Helai (f)  Heley (f)  Helo (m)  Hena'é'héhe (f)  Heóveaénohe (m)  Heyao (f)  Heyiyw (m)  Hezhi (m,f)  Hibari (f)  Hierax (m)  Higura (m,f)  Hisui (f)  Hohtȧhéaénohe (m)  Holló (m)  Hongai (f)  Hongbin (m,f)  Hongbo (m,f)  Hongjia (m,f)  Hongjun (m,f)  Hongli (f)  Hongwei (m,f)  Hongying (f,m)  Hongyu (m,f)  Hongyuan (f)  Hongzhang (m)  Hongzhi (m)  Hosa (m)  Houng (f)  Hræfn (m)  Hrafndís (f)  Hrafney (f)  Hrafnfífa (f)  Hrafngerður (f)  Hrafnheiður (f)  Hrafnkell (m)  Hrafntinna (f)  Hrafntýr (m)  Hrókr (m)  Huacmitl (m)  Huactli (m)  Huanlu (f)  Huilotl (f)  Huitzilatl (m)  Huitzilcuauh (m,f)  Huitzilihuitl (m)  Huitziltemoc (m)  Huitzilxochtzin (f)  Huitzitl (m,f)  Ibid (m)  Icnocuauh (m)  Ikrimah (m,f)  Inaiê (f)  Inghiramo (m)  Iolani (f)  Itsu (f)  Itza-chu (m)  Itzcuauh (m)  Itzcuauhtli (m)  Jandaia (f)  Jarli (m)  Jauna (f)  Jedda (f)  Jémpe (m)  Jialu (f)  Jingul (f)  Jinlu (f)  Jinyan (f,m)  Jiu (f)  Joceran (m)  Joddur (m,f)  Jojji (m)  Jonuo (m)  Joutsi (m,f)  Junna (f)  Junnosuke (m)  Junro (m)  Juntarou (m)  Kabutar (f)  Kaifa (f,m)  Kaija (f)  Kaiva (f)  Kalāg (m)  Kalas (m)  Kanan (m,f)  Kangee (m,f)  Kangoĸ (m)  Kanut (f,m)  Kapot (f)  Kaptar (f)  Karasu (m)  Karasu (f,m)  Karawek (f,m)  Kārearea (f,m)  Kargata (m)  Kariko (f)  Karlygash (f)  Kartal (m)  Kartiğa (m)  Kass (m,f)  Katsue (f)  Katsutaka (m)  Kauã (m)  Kauanny (f)  Kaur (m)  Keika (f,m)  Kekhan (m)  Kele (m)  Kevok (f)  Khallwa (f)  Khartsaga (m)  Khaylin (m)  Khotoy (m)  Kinga (m)  Koa (m)  Kodee (f)  Kögürçün (f)  Kohkahycumest (m)  Kökecü (m,f)  Kontara (f)  Korak (m)  Korpr (m)  Kosagi (f)  Kosovka (f)  Kotori (m)  Kotsuru (f)  Kou (m,f)  Koulm (m)  Koyah (m)  Koyal (f)  Krákr (m)  Kuarasa (f)  Kuğu (f)  Kuira (m)  Kuja (m)  Kujaku (f,m)  Kukulí (f)  Küöregeyçeene (f)  Kurak (m)  Kuronue (m)  Kutskan (m)  Kuyra (m)  Kuzco (m)  Kuzgun (m,f)  Kwahu (m)  Kypselos (m)  Kytaliina (f)  Kyura (m)  Łabędz (f)  Labud (m)  Laouenan (m)  Lashyn (f,m)  Lauresha (f)  Lautaro (m)  Lecha (m)  Liangying (f)  Lianjuan (f)  Lifri (m)  Liluye (f)  Linlu (f)  Linyan (f)  Liutram (m)  Lochinoy (f)  Lodoletta (f)  Longcui (f)  Longyan (f)  Longying (f,m)  Lufei (f)  Luhong (f)  Luli (f)  Luling (f)  Luscinia (f)  Lushanya (f)  Lutang (f)  Luv (f)  Luyao (f)  Ma'eméstahke (m)  Ma'enetse (m)  Magpie (f)  Mahkate:wi-meši-ke:hke:hkwa (m)  Makya (f,m)  Mamani (m)  Mamizu (f)  Maphoi (f)  Már (m,f)  Marlette (f)  Maroochy (f)  Matlaccuauh (m)  Matuku (m,f)  Mayank (m)  Mayoor (m)  Mayuri (f)  Meihe (f)  Meique (f)  Menghong (f)  Menglu (f)  Merula (m)  Michika (f,m)  Mierla (f)  Mihiro (f,m)  Mingcui (f)  Minying (f,m)  Mis-stan-stur (f)  Miteĸ (m)  Miteraĸ (f)  Mitsuru (f,m)  Miyan (f)  Mjellma (f)  Mo' (m)  Molotl (m)  Momosoch (f)  Momozuru (f)  Mongwau (m)  Naajaraq (f)  Nachin (f,m)  Nachyn (m)  Nagtoralik (m)  Nanyan (f)  Narakatangetu (m,f)  Nascha (f)  Natsuru (f)  Naujánguaĸ (f)  Naujardluk (f)  Nengyan (f)  Nerdlâĸ (f)  Nessus (m)  Nianyan (f)  Niaowu (f)  Ninglu (f)  Njive (f)  Nkanga (m)  Nobutaka (m)  Nokka (f)  Nokyung (f)  Nona (m,f)  Noritaka (m)  Ntsu (m)  Nyenganyenga (f)  Ókȯhkėho'ēsta (m)  Ókȯhkéso (m)  Ókȯhkeveho (m)  Ókȯhkevó'omaestse (m)  Oltinsoch (f)  Omecuauh (m,f)  O'Peqtaw-Metamoh (f)  Oreb (m)  Orenthal (m)  Orlaw (m)  Orlin (m)  Örn (m)  Orri (m)  Örtek (f)  Orthros (m)  Oryol (m)  Oryol (m)  Otá'taveaénohe (m)  Otoncuauh (m)  Otos (m)  Otran (m)  Ou (m)  Oyto'ti (f)  Oytovus (f)  Ozuru (m)  Paka Wara (f)  Pakhom (m)  Palomba (f)  Parçıkh (f)  Pasian (f)  Patig (m)  Păuna (f)  Pavun (m)  Peiyan (f)  Pëllumbesha (f)  Peristera (f)  Phakalane (m)  Phirap (m)  Pihew-kamihkosit (m)  Pinon (m)  Pintyőke (f)  Preap (m,f)  Putta (m)  Pya (f)  Pykasu (f)  Qaldirg'och (f)  Qarasa (f)  Qarliğaş (f)  Qianghong (f)  Qiangying (f,m)  Qianhe (f,m)  Qianlu (f)  Qianyan (f)  Qianying (f)  Qiaoe (f)  Qiaoyan (f,m)  Qingyan (f)  Qiongyan (f)  Qoqa (f)  Qorasoch (f)  Q'orianka (f)  Quauhchimal (m)  Quauhtlapochin (m)  Quauhtliztac (m)  Quechollacahua (f)  Quenah-evah (m)  Quetzal (m,f)  Quetzala (f)  Quetzalcuauh (m)  Quetzalhua (m)  Quetzalmitl (m)  Quetzalxochitl (f)  Quikinna'qu (m)  Quloqutsuk (m)  Qumrî (f)  Qumru (f)  Rabe (m)  Rakuen (m)  Rambald (m)  Ramfrid (m)  Ramtrud (f)  Ramund (m)  Ramward (m)  Ranne (f)  Ransley (m)  Ranulf (m)  Rauke (m)  Ravna (f)  Remaclus (m)  Remme (m)  Remmelt (m)  Reshin (m,f)  Rihe (f)  Ritchåd (m)  Rjúpa (f)  Robinhood (m)  Roek (m)  Rotram (m)  Rubenis (m)  Ruiyan (f)  Ruru (m)  Saaskhan (f)  Sagi (m,f)  Saiyan (f)  Sakalas (m)  Sak-kʼukʼ (f)  Salaram (m)  Sandugas' (f)  Sandugash (f)  Saqr (m)  Sarankhökhöö (m,f)  Sarig (f)  Sarika (f)  Saylykmaa (f)  Schwaniger (m)  Sépistòkòs (m)  Shabahang (f)  Shahaf (m,f)  Shahbaz (m)  Shahboz (m)  Shahen (m)  Shangcui (f)  Shaoyan (f)  Shavacha (m)  Shengcui (f)  Shengyan (f)  Shevardena (m)  Shӑnkӑrch (m)  Shonkhor (m,f)  Shqiponja (f)  Shunta (m)  Shuyan (f)  Shyakshata (m)  Sicleramna (f)  Siginak (m)  Sigram (m)  Sigurörn (m)  Sihong (f)  Siluna (f)  Simurg (f)  Sindram (m)  Sinma (f)  Siramarg (f)  Skifter (m)  Slavuj (m)  Sochbibi (f)  Sochoy (f)  Sójka (f)  Sokhag (f)  Sólyom (m)  Songcui (f)  Songyan (f,m)  Songying (f,m)  Soo-ri (m,f)  Soua (f)  Spearhafoc (m)  Spǫrr (m)  Stari (m)  Starri (m)  Stolas (m)  Sturla (m)  Sülgün (f)  Sun (m,f)  Suwan (f)  Suzaku (m,f)  Sval (f)  Svala (f)  Svalrún (f)  Svanaug (f)  Svanbjörn (m)  Svanbjört (f)  Svanborg (f)  Svandís (f)  Svaney (f)  Svanfríður (f)  Svanhólm (m)  Svanhvít (f)  Svanlaug (f)  Svanr (m)  Svanrós (f)  Svanrun (f)  Svanþór (m)  Svanþrúður (f)  Swanabald (m)  Swanabert (m)  Swanaburg (f)  Swanagard (f)  Swanagild (f)  Swantje (f)  Syulga (m)  Taalika (f)  Tadataka (m)  Tagwilalt (f)  Tahatan (m)  Taka (m,f)  Takaichirou (m)  Takamaru (m)  Takamasa (m)  Takami (m,f)  Takaomi (m)  Takashige (m)  Tamanajko (m)  Tarlan (m)  Tasqara (m)  Tatbirt (f)  Taube (f)  Taulant (m)  Tawus (m)  Tawus (f)  Tecolotl (m,f)  Tekāhu (m,f)  Tentagays (f)  Tequechol (m)  Tercia (f)  Teutobod (m)  Thanina (f)  Theuderam (m)  Þrǫstr (m)  Thúy (f,m)  Þyrill (m)  Tiange (f)  Tianyan (f)  Tingyan (f)  Tjorven (m,f)  Tlacatecolotl (m)  Tlohui (m)  Togos (m,f)  Togosgerel (m,f)  Tokino (f)  Tokito (m)  Tokori (m)  Tongyan (f)  Tor (m,f)  Toray (m)  Torgaý (m)  Torkan (m)  Tôrnavia (f)  Toshitaka (m)  Toshto'xta (m)  To'ti (f)  To'tigul (f)  Toty (f)  Tovus (f)  To'xta (m)  To'xtaali (m)  To'xtamurod (m)  To'xtaniyoz (m)  To'xtaoxun (m)  To'xtapo'lat (m)  To'xtaqilich (m)  To'xtaqo'zi (m)  Tozcuecuextli (m)  Tozmacuex (m)  Trĩ (f)  Tringë (f)  Tsio:kwaris (m)  Tsobako (f)  Tsonkiri (f,m)  Tsu-la (m)  Tsúntsumanch (f)  Tsuruchiyo (m,f)  Tsurue (f)  Tsuruko (f)  Tsurukoma (f)  Tsurumi (f)  Tsuruno (f)  Tsuruo (m)  Tsuruya (m,f)  Tsuruya (m,f)  Tsuruyo (f)  Tsyofks (m)  Tûgdlik (f)  Turna (f)  Turnaxol (f)  Turuya (f)  Tuti (f)  Tuuğan (m)  Tuyg'un (m)  Tuyg'unjon (m)  Tyjah (m,f)  Ugla (f)  Ugluspegill (m)  Ugo (m,f)  Ugonna (m)  Ügü (f)  Uilke (m)  Ukkiboy (m)  Ular (m)  Úlfarna (f)  Unkalla (f)  Urpicha (f)  Urpikusi (f)  Urpila (f)  Urraca (f)  Uyên (f)  Varash (m)  Varqa (m)  Vidan (m)  Vóaxaa'éma'heóná'e (f)  Vóaxaa'éméóná'e (f)  Vóaxaa'ȯhnéstooestse (m)  Vóaxaa'ȯhvó'komaestse (m)  Vóestȧhmo'ȯhtávaestse (m)  Vóestāso (m)  Vóestȧsóeméóná'e (f)  Vóhpeaénohe (m)  Vóhpeméstaa'e (m)  Vóo'kooma (m)  Voron (m)  Wachapéa (m)  Walaram (m)  Walderam (m)  Wamblee (m)  Wamlisapa (f)  Wangyan (f)  Wanhong (f)  Wanwu (f,m)  Wanyan (f)  Waqar (f)  Washio (m)  Washoe (m)  Weiyan (f,m)  Wenlu (f)  Wenyan (f,m)  Wigram (m)  Wilfram (m)  Williram (m)  Wohali (m)  Woya (f)  Wrenna (f)  Wuyi (m)  Xawan (m,f)  Xhuuyaa (m)  Xiange (f)  Xianghong (f,m)  Xiangying (f)  Xianyan (f)  Xiaocui (f)  Xiaoge (f)  Xiaoxian (f)  Xiaoyan (f,m)  Xilu (f)  Xinhong (f)  Xinlu (f)  Xinyan (f)  Xiuge (f)  Xiuhong (f)  Xiyan (f,m)  Xuecui (f)  Xuefei (f)  Xuejuan (f)  Xunyan (f)  Xuthus (m)  Xuyan (f)  Xuying (f,m)  Yahong (f)  Yakyuu (m)  Yamam (m,f)  Yamha (f)  Yanbei (f)  Yanchen (f)  Yanfei (f,m)  Yangwu (f)  Yanhong (f,m)  Yanhua (f,m)  Yanju (f)  Yanjun (m,f)  Yanle (f)  Yanlin (f)  Yanling (f,m)  Yanlong (f)  Yanlun (f)  Yanming (m,f)  Yanpeng (f)  Yanping (f,m)  Yanqi (f)  Yanqin (f)  Yanqing (f,m)  Yanqiu (f)  Yanren (f)  Yanshan (f)  Yanshao (f)  Yansheng (f)  Yanshui (f)  Yansong (f,m)  Yanwa (f)  Yanxi (f)  Yanxia (f)  Yanxiang (f)  Yanxin (f)  Yanxu (f)  Yanxun (f)  Yanyan (f,m)  Yanyou (f)  Yanyuan (f)  Yanzhen (f)  Yanzhi (f)  Yaqulpak (m)  Yayan (f)  Yến (f,m)  Yeyan (f)  Yihui (f,m)  Yinghe (f)  Yingli (f)  Yingniao (f)  Yingqing (f)  Yinhe (f)  Yinlu (f)  Yinyan (f)  Yiying (f,m)  Yonghong (m,f)  Yongyan (f,m)  Yoritaka (m)  Youki (m)  Youyan (f)  Yuecui (f)  Yueguan (f)  Yuehong (f)  Yuejuan (f)  Yueyan (f)  Yueying (f)  Yuguan (f)  Yükserge (m)  Yüksüdyr (f)  Yunlu (f)  Yuyan (f)  Zaghlul (m)  Zamir (m)  Zanzīru (m)  Zarka (f)  Zengyan (f)  Zhaojun (f)  Zhaoyan (f)  Zhenghong (m)  Zhenlu (f)  Zhihong (m,f)  Zhiyan (f)  Zhongcui (f)  Zhshibés (m)  Zhucui (f)  Zhuiyan (f)  Zhuque (m)  Zhuyan (f)  Zihe (f)  Zīle (f)  Ziyan (f)  Ziying (f)  Zonga (f)  Zwane (f)
	Antiman (m)  Aucaman (m)
	Condorito (m)
Gallus (m)
Atahualpa (m)
Alectrona (f)  Alectryon (m)  Alektor (m)  Cacark’a (f)  Cihuatotocatl (m)  Curca (f)  Dậu (f)  Electryone (f)  Gai (f)  Hanno (m)  Kana (f,m)  Kaða (m)  Kike (m)  Lija (f)  Liluye (f)  Manato (m)  Obai (f,m)  Olio (m)  Orneus (m)  Ornytos (m)  Orthros (m)  Piyoton (f)  Putinas (m)  Qaib (f)  Tamami (f)  Žemyna (f)
Baojuan (f)  Chanjuan (f)  Chash-köök (m)  Cuco (m)  Dzeguze (f)  Karawek (f,m)  Koyal (f)  Lianjuan (f)  Sarankhökhöö (m,f)  Xuejuan (f)  Yuejuan (f)
Koronis (f)  Rocco (m)  Vasco (m)
Crawford (m)  Isapo-Muxika (m)  Mekaisto (m)
Algorab (m)  Angwusnasomtaqa (f)  Badb (f)  Beila (m)  Boduognatos (m)  Branoc (m)  Bugafer (f,m)  Cathubodua (f)  Cynfran (m)  Fainche (f)  Fala (f)  Gargabay (m)  Hosa (m)  Hrókr (m)  Kalāg (m)  Kalas (m)  Kangee (m,f)  Karasu (m)  Karasu (f,m)  Koa (m)  Korak (m)  Krákr (m)  Kurak (m)  Niaowu (f)  Nokka (f)  Ókȯhkėho'ēsta (m)  Ókȯhkéso (m)  Ókȯhkeveho (m)  Ókȯhkevó'omaestse (m)  Orthros (m)  Roek (m)  Soua (f)  Teutobod (m)  Tjorven (m,f)  Voron (m)  Wanwu (f,m)
Sona 2 (f)  Suna (f)
Ahiru (f)  Angir (m,f)  Banzou (m)  Chilcanauh (m)  Cochcanauh (m,f)  Dongyang (f)  Dúna (f)  Galgan-nga (f)  Helai (f)  Miteĸ (m)  Miteraĸ (f)  Nessus (m)  Örtek (f)  Patig (m)  Tôrnavia (f)  Unkalla (f)  Uyên (f)  Yangwu (f)  Zhshibés (m)
Adler (m)  Aetius (m)  Ane 2 (m)  Anne 2 (m)  Aquila (m,f)  Aras (m)  Ari 2 (m)  Arke 2 (m)  Arne 1 (m)  Arūnas (m)  Shqipe (f)  Tahlako (m)  Waman (m)  Wambdi (m,f)  Wambli (m,f)
Andor 1 (m)  Ankarl (m)  Antinanco (m)  Arnar (m)  Arnbjǫrg (f)  Arnfinn (m)  Arnfried (m)  Arnoald (m)  Arnold (m)  Arnsteinn (m)  Arnulf (m)  Arvid (m)  Cuauhtemoc (m)  Haytham (m)  Þórarinn (m)  Ugochi (f)  Ugochukwu (m)
Acuauh (m)  Æringunnr (f)  Ærinví (f)  Ærngautr (m)  Águila (f)  Akhom (m)  Akleja (f)  Aladfar (f)  Alathfar (f)  Alfarinn (m)  Alkhazur (m)  Amke (f)  Anzû (m)  Aquillius (m)  Arabert (m)  Aragund (f)  Aramund (m)  Ard (m)  Arda (f)  Ardin (m)  Ardziv (m)  Ardzvig (f)  Aregis (m)  Arendje (m,f)  Arhild (f)  Ariwald (m)  Arna (f)  Arnas (m)  Arnbert (m)  Arnbjörn (m)  Arnbrand (m)  Arnbrandr (m)  Arndís (f)  Arnevi (f)  Arnfastr (m)  Arnfrid (f)  Arnfríðr (f)  Arnfrøðr (m)  Arngeirr (m)  Arngerðr (f)  Arngrímr (m)  Arnheiðr (f)  Arnhildr (f)  Arnhǫfði (m)  Arnida (f)  Arnketill (m)  Arnlaug (f,m)  Arnlín (f)  Arnljótr (m)  Arnmóðr (m)  Arnmundr (m)  Arnniútr (m)  Arnrós (f)  Arnrún (f)  Arnþjófr (m)  Arnþrúðr (f)  Arnulfr (m)  Arnveig (f)  Arnwin (m)  Arny (f)  Arulf (m)  Arvin (m)  Atsa (f)  Aztlan (m,f)  Banoy (m)  Bennu (f)  Bürged (m)  Burgutoy (f)  Burkit (m)  Bürkitbay (m)  Cecuauh (m)  Chamuk (f)  Chiconcuauh (m)  Chilina (f)  Chimalcuauhtli (m)  Chunying (f,m)  Cuauhatl (m)  Cuauhcoatl (m,f)  Cuauhcopil (m)  Cuauhicopi (m)  Cuauhihuitl (m)  Cuauhilama (m)  Cuauhnecahual (m)  Cuauhnenemi (m)  Cuauhpan (m)  Cuauhpopoca (m)  Cuauhquen (m,f)  Cuauhquiyahuacatl (m)  Cuauhtapalca (m)  Cuauhtecolotl (m)  Cuauhtecpan (m)  Cuauhtepotzo (m)  Cuauhtilma (m)  Cuauhtin (m)  Cuauhtlamati (m)  Cuauhtlapetz (f)  Cuauhtlapeuh (m)  Cuauhtlatoa (m)  Cuauhtlatoatzin (m)  Cuauhtlatzacuilotl (m)  Cuauhtlaxaya (m)  Cuauhtli (m,f)  Cuauhtlichimal (m)  Cuauhtopilli (m)  Cuauhtzitzimitl (m)  Cuauhtzontecon (m)  Cuauhxilotl (m,f)  Cuauhyollo (m)  Cuauhzton (m)  Earngeat (m)  Earngith (f)  Earnsige (m)  Earnweald (m)  Earnwig (m)  Earnwine (m)  Earnwulf (m)  Edahna (f)  Eheder (m)  Ehrentraud (f)  Eitam (m)  Ēkara (f,m)  Elang (m)  Elya (m)  Erelis (m)  Erngeat (m)  Ernoul (m)  Garuda (m)  Gorbat (m)  Haiying (f,m)  Harapšeki (f)  Ḫarapšili (f)  Huitzilcuauh (m,f)  Icnocuauh (m)  Itza-chu (m)  Itzcuauh (m)  Itzcuauhtli (m)  Joddur (m,f)  Jojji (m)  Jonuo (m)  Kartal (m)  Khotoy (m)  Kodee (f)  Kutskan (m)  Kwahu (m)  Ma'enetse (m)  Makya (f,m)  Matlaccuauh (m)  Minying (f,m)  Nagtoralik (m)  Nkanga (m)  Ntsu (m)  Omecuauh (m,f)  O'Peqtaw-Metamoh (f)  Orenthal (m)  Orlaw (m)  Orlin (m)  Örn (m)  Oryol (m)  Oryol (m)  Otoncuauh (m)  Ou (m)  Paka Wara (f)  Pakhom (m)  Phakalane (m)  Q'orianka (f)  Quauhchimal (m)  Quauhtlapochin (m)  Quauhtliztac (m)  Quenah-evah (m)  Quetzalcuauh (m)  Shqiponja (f)  Sigurörn (m)  Simurg (f)  Soo-ri (m,f)  Takaichirou (m)  Takami (m,f)  Thanina (f)  Ugo (m,f)  Ugonna (m)  Ukkiboy (m)  Úlfarna (f)  Vóaxaa'éma'heóná'e (f)  Vóaxaa'éméóná'e (f)  Vóaxaa'ȯhnéstooestse (m)  Vóaxaa'ȯhvó'komaestse (m)  Wamblee (m)  Wamlisapa (f)  Washio (m)  Washoe (m)  Wohali (m)  Yaqulpak (m)  Youki (m)
Çağrı (m,f)  Cauã (m)  Csongor (m)  Falk (m)  Kestrel (f)  Petrit (m)  Shahin (m)  Sokol (m)  Waman (m)
Ákos (m)  Erdoğan (m)  Hayato (m)
Aiah (m)  Alsïnbikä (f)  Ayah (m,f)  Aydoğan (f,m)  Bahrin (f)  Baz (m)  Baze (m)  Bazê (f)  Bozgul (f)  Chaytan (m)  Cheglok (m)  Chunying (f,m)  Dilbaz (f)  Doğan (m)  Elang (m)  Falcon (m)  Falcona (f)  Falkny (f)  Falkon (m)  Gerakina (f)  Gulboz (f)  Gurbaaz (m)  Haiying (f,m)  Hayahito (m)  Hayaichirou (m)  Hayakazu (m)  Hayao (m)  Hayase (m)  Hayata (m)  Hayatarou (m)  Hayuma (m,f)  Heyiyw (m)  Hierax (m)  Huacmitl (m)  Huactli (m)  Junna (f)  Junnosuke (m)  Junro (m)  Juntarou (m)  Kārearea (f,m)  Kartal (m)  Kauã (m)  Kyura (m)  Lashyn (f,m)  Lecha (m)  Lochinoy (f)  Minying (f,m)  Nachin (f,m)  Nachyn (m)  Ou (m)  Pakhom (m)  Sakalas (m)  Saqr (m)  Shahbaz (m)  Shahboz (m)  Shevardena (m)  Shonkhor (m,f)  Shunta (m)  Skifter (m)  Sólyom (m)  Sun (m,f)  Tahatan (m)  Takaichirou (m)  Takami (m,f)  Takashige (m)  Tarlan (m)  Tercia (f)  Tuuğan (m)  Youki (m)  Zonga (f)
Astor (m)  Cauã (m)  Circe (f)  Şahin (m)
Aenoheso (m)  Erdoğan (m)  Gwalchmai (m)  Qinnuajuaq (f,m)
Acuauh (m)  Aénohe (m)  Aénȯhea'eotse (m)  Aénȯhéévé'hȧhtse (m)  Aénȯheméóná'e (f)  Aénȯhenéhovóhe (m)  Ajah (m)  Akitaka (m)  Aktuygun (f)  Astore (m)  Baze (m)  Cetanwakuwa (m)  Chaytan (m)  Ches-kartiğa (m)  Chunying (f,m)  Dilbaz (f)  Doğan (m)  Falco (m)  Fumitaka (m)  Gawen (m)  Gerakina (f)  Gjeraqina (f)  Gwain (m)  Gwalchgwyn (m)  Haiying (f,m)  Hauk (m)  Haukr (m)  Hauksteinn (m)  Haukur (m)  Hawkeye (m,f)  Helo (m)  Heóveaénohe (m)  Heyiyw (m)  Hierax (m)  Hohtȧhéaénohe (m)  Inaiê (f)  Iolani (f)  Itza-chu (m)  Kartal (m)  Kartiğa (m)  Katsutaka (m)  Kauanny (f)  Khartsaga (m)  Kuira (m)  Kuyra (m)  Lautaro (m)  Liluye (f)  Mahkate:wi-meši-ke:hke:hkwa (m)  Mamani (m)  Minying (f,m)  Nobutaka (m)  Noritaka (m)  Otá'taveaénohe (m)  Ou (m)  Putta (m)  Shahbaz (m)  Shahen (m)  Shevardena (m)  Shonkhor (m,f)  Spearhafoc (m)  Tadataka (m)  Tahatan (m)  Taka (m,f)  Takaichirou (m)  Takamaru (m)  Takamasa (m)  Takami (m,f)  Takaomi (m)  Tekāhu (m,f)  Tercia (f)  Tlohui (m)  Toshitaka (m)  Tuyg'un (m)  Tuyg'unjon (m)  Varash (m)  Vóhpeaénohe (m)  Yoritaka (m)  Youki (m)
Astor (m)  Cauã (m)  Circe (f)  Şahin (m)
Aenoheso (m)  Erdoğan (m)  Gwalchmai (m)  Qinnuajuaq (f,m)
Acuauh (m)  Aénohe (m)  Aénȯhea'eotse (m)  Aénȯhéévé'hȧhtse (m)  Aénȯheméóná'e (f)  Aénȯhenéhovóhe (m)  Ajah (m)  Akitaka (m)  Aktuygun (f)  Astore (m)  Baze (m)  Cetanwakuwa (m)  Chaytan (m)  Ches-kartiğa (m)  Chunying (f,m)  Dilbaz (f)  Doğan (m)  Falco (m)  Fumitaka (m)  Gawen (m)  Gerakina (f)  Gjeraqina (f)  Gwain (m)  Gwalchgwyn (m)  Haiying (f,m)  Hauk (m)  Haukr (m)  Hauksteinn (m)  Haukur (m)  Hawkeye (m,f)  Helo (m)  Heóveaénohe (m)  Heyiyw (m)  Hierax (m)  Hohtȧhéaénohe (m)  Inaiê (f)  Iolani (f)  Itza-chu (m)  Kartal (m)  Kartiğa (m)  Katsutaka (m)  Kauanny (f)  Khartsaga (m)  Kuira (m)  Kuyra (m)  Lautaro (m)  Liluye (f)  Mahkate:wi-meši-ke:hke:hkwa (m)  Mamani (m)  Minying (f,m)  Nobutaka (m)  Noritaka (m)  Otá'taveaénohe (m)  Ou (m)  Putta (m)  Shahbaz (m)  Shahen (m)  Shevardena (m)  Shonkhor (m,f)  Spearhafoc (m)  Tadataka (m)  Tahatan (m)  Taka (m,f)  Takaichirou (m)  Takamaru (m)  Takamasa (m)  Takami (m,f)  Takaomi (m)  Tekāhu (m,f)  Tercia (f)  Tlohui (m)  Toshitaka (m)  Tuyg'un (m)  Tuyg'unjon (m)  Varash (m)  Vóhpeaénohe (m)  Yoritaka (m)  Youki (m)
Cacark’a (f)  Cihuatotocatl (m)  Curca (f)  Kana (f,m)  Kaða (m)  Lija (f)  Olio (m)  Žemyna (f)
Alcyone (f)  Halcyon (f) Aomi (f,m)  Cuichang (f)  Cuie (f)  Cuifen (f)  Cuili (f)  Cuiliang (f)  Cuiling (f)  Cuiluan (f)  Cuiming (f)  Cuiping (f)  Cuiquan (f)  Cuisheng (f)  Cuitao (f)  Cuixiang (f)  Cuixin (f)  Cuiyin (f)  Cuiying (f)  Cuiyuan (f)  Cuiyue (f)  Cuizhao (f)  Decui (f)  Fanfei (f)  Feilin (f)  Feitang (f)  Hisui (f)  Longcui (f)  Lufei (f)  Michika (f,m)  Mihiro (f,m)  Mingcui (f)  Shangcui (f)  Shengcui (f)  Songcui (f)  Thúy (f,m)  Þyrill (m)  Tsu-la (m)  Xiaocui (f)  Xuecui (f)  Xuefei (f)  Yuecui (f)  Zhongcui (f)  Zhucui (f) Diindiisi (f,m) Jacey (f,m)  Jaden (m,f)  Jalen (m)  Javion (m)  Javon (m)  Jaycee (f,m)  Jayla (f)  Jaylah (f)  Jaylee (f)  Jayleen (f)  Jaylene (f)  Jaylinn (f)  Jaylyn (f)  Jaylynn (f)
Colas (m)  Djeråd (m)  Djuråd (m)  Ritchåd (m)  Shavacha (m)  Sójka (f)  Tyjah (m,f)
Mayur (m) Altantogos (f,m)  Chandrakin (f)  Deepshikha (f)  Gultovus (f)  Kuja (m)  Kujaku (f,m)  Mayank (m)  Mayoor (m)  Mayuri (f)  Nokyung (f)  Oytovus (f)  Păuna (f)  Pavun (m)  Siramarg (f)  Tawus (m)  Tawus (f)  Togos (m,f)  Togosgerel (m,f)  Tovus (f)
Atotoztli (f)  Bawan (m,f)  Chamol (m)  Chamolmani (m)  Danying (f)  Jandaia (f)  Kanan (m,f)  Mo' (m)  Narakatangetu (m,f)  Niaowu (f)  Oyto'ti (f)  Reshin (m,f)  To'ti (f)  To'tigul (f)  Toty (f)  Tozcuecuextli (m)  Tozmacuex (m)  Tuti (f)  Wachapéa (m)  Xawan (m,f)
Yaen (f) Beid (m,f)  Theemin (f,m)  Zibal (m) Sarika (f) Kaifa (f,m)  Pasian (f)  Pihew-kamihkosit (m)  Sülgün (f)  Tequechol (m)  Trĩ (f)  Xiaoxian (f)  Yihui (f,m)
Phoenix (m,f)  Phượng (f) Huang (m,f) Bong-ju (m)  Bongseok (m)  Charani (f)  Espella (f)  Feng (m,f)  Fengjiao (f)  Fengqing (f,m)  Fengye (f,m)  Fengying (f)  Foong (m,f)  Haebong (m)  Hakuoh (m,f)  Hoàng (m,f)  Huangrong (f)  Jiufeng (m,f)  Kourei (f,m)  Lifeng (m)  Mokou (f)  Phụng (m,f)  Punig (m)  Xiaofeng (m,f)  Xifeng (f,m)  Yanfeng (m,f)  Ye-bong (f)  Yifeng (m,f)  Yufeng (m,f)  Yuhuang (f)
Gallus (m) Alectrona (f)  Alectryon (m)  Alektor (m)  Dậu (f)  Electryone (f)  Hanno (m)  Kike (m)  Obai (f,m)  Orthros (m)  Putinas (m)  Žemyna (f)
Hong (m,f)  Svanhild (f)  Swanahildiz (f)  Swanhild (f) Akku (f)  Aqqoš (f)  Aqqw (m,f)  Bihong (f)  Cisne (f,m)  Cygnet (f)  Éala (f)  Elphir (m)  Fuhong (f)  Gedia (m,f)  Gelgéis (f)  Hamsika (f)  Hansika (f)  Hansini (f)  Hansita (f)  Helai (f)  Heley (f)  Hongai (f)  Hongbin (m,f)  Hongbo (m,f)  Hongjia (m,f)  Hongjun (m,f)  Hongli (f)  Hongwei (m,f)  Hongying (f,m)  Hongyu (m,f)  Hongyuan (f)  Hongzhang (m)  Hongzhi (m)  Houng (f)  Joutsi (m,f)  Kuğu (f)  Łabędz (f)  Labud (m)  Luhong (f)  Maroochy (f)  Menghong (f)  Mjellma (f)  Qianghong (f)  Quechollacahua (f)  Schwaniger (m)  Sihong (f)  Suwan (f)  Svanaug (f)  Svanbjörn (m)  Svanbjört (f)  Svanborg (f)  Svandís (f)  Svaney (f)  Svanfríður (f)  Svanhólm (m)  Svanhvít (f)  Svanlaug (f)  Svanr (m)  Svanrós (f)  Svanrun (f)  Svanþór (m)  Svanþrúður (f)  Swanabald (m)  Swanabert (m)  Swanaburg (f)  Swanagard (f)  Swanagild (f)  Swantje (f)  Wanhong (f)  Xianghong (f,m)  Xinhong (f)  Xiuhong (f)  Yahong (f)  Yonghong (m,f)  Yuehong (f)  Yükserge (m)  Yüksüdyr (f)  Zhenghong (m)  Zhihong (m,f)  Zwane (f) Paloma (f)  Urpi (f)  Pelias (m) Baige (f)  Balandis (m)  Enkhtagtaa (m,f)  Fa'alupe (f,m)  Fangge (f)  Galabin (m)  Golubitsa (f)  Hatoko (f)  Hatomi (f)  Ikrimah (m,f)  Jiu (f)  Kabutar (f)  Kaptar (f)  Kevok (f)  Khaylin (m)  Palomba (f)  Pëllumbesha (f)  Peristera (f)  Phirap (m)  Preap (m,f)  Pykasu (f)  Qoqa (f)  Qumrî (f)  Shonkhor (m,f)  Tiange (f)  Urpicha (f)  Urpikusi (f)  Vidan (m)  Xiange (f)  Xiaoge (f)  Xiuge (f)  Yakyuu (m)  Zaghlul (m)  Paloma (f)  Urpi (f) Pelias (m) Baige (f)  Balandis (m)  Enkhtagtaa (m,f)  Fa'alupe (f,m)  Fangge (f)  Galabin (m)  Golubitsa (f)  Hatoko (f)  Hatomi (f)  Ikrimah (m,f)  Jiu (f)  Kabutar (f)  Kaptar (f)  Kevok (f)  Khaylin (m)  Palomba (f)  Pëllumbesha (f)  Peristera (f)  Phirap (m)  Preap (m,f)  Pykasu (f)  Qoqa (f)  Qumrî (f)  Shonkhor (m,f)  Tiange (f)  Urpicha (f)  Urpikusi (f)  Vidan (m)  Xiange (f)  Xiaoge (f)  Xiuge (f)  Yakyuu (m)  Zaghlul (m)
 (f) Aoileann (f)  Aqsarlaq (f)  Faílenn (f)  Faoileán (m,f)  Gwylan (f)  Kaija (f)  Kaiva (f)  Kekhan (m)  Már (m,f)  Naajaraq (f)  Naujánguaĸ (f)  Naujardluk (f)  Ou (m)  Shahaf (m,f)  Syulga (m)  Tsúntsumanch (f)



OWL:
 Ruru (m)  Sépistòkòs (m)  Stolas (m)  Tamanajko (m)  Tecolotl (m,f)  Tlacatecolotl (m)  Tokori (m)  Tsobako (f)  Ugla (f)  Ugluspegill (m)  Ügü (f)  Uilke (m)  Ukkiboy (m)  Vóhpeméstaa'e (m)
Dror (m)  Sparrow (m,f)
Asfour (m)  Gealbhán (m)    Quloqutsuk (m)  Spearhafoc (m)
  (m)  Xuthus (m)  Zhuque (m)





- CROW & Ravens
'''

def Names(genus):
	MALE    = "He"    in genus
	FEMALE  = "She"   in genus
	AGENDER = "They"  in genus
	genus = genus
	Names = []

	SUBgenus = "Subgenus" in genus

	Names += [
	"Flit", "Glide", "Mimic", "Echo",
	"Shimmer", "Talon", "Plume",
	"Soar", "Shade",
	"Dusk", "Dawn",
	"Twilight",
	"Nightcall",
	"Wingbeat",
	"Rustle",
	"Murmur", "Feather",
	"Perch",
	"Roost", "Glitter", "Beaksharp",
	"Swoop", "Windrider",
	"Cloudwing", "Skydance",
	"Mooncaw",
	"Sunfeather",
	"Starshine", "Hoopoe",
	"Chatter", "Squawk",
	"Preen", "Beacon", "Ruffle",
	"Silhouette",
	"Frostwing",
	"Skyshriek",
	"Windwhisper",
	"Nighthawk", "Skygleam",
	"Stormwatch",
	"Raincry", "Snowplume",
	"Thundercaw", "Windfeather", "Songthief",
	"Eclipsing", "Shadowplay", "Sunshadow",
	"Pinnacle", "Crest", "Echoflap",
	"Nestling", "Skyward", "Sable", "Flock",
	"Whistle",
	"Hush",
	"Lustrous",
	"Mottle",
	"Pepper",
	"Tint",
	"Hue",
	"Canvas",
	"Sketch",
	"Inkfeather",
	"Jewel", "Gemwing",
	"Prism", "Spectra",
	"Ripple", "Glisten",
	"Gleam",
	"Harmony", "Rhythm",
	"Melody", "Crescendo",
	"Lilt", "Aria",
	"Sonnet",
	"Verse", "Chorus", "Note", "Chime", "Bell",
	"Tune", "Clef", "Lyric",
	"Resonate", "Hum",
	"Whirl", "Echoing",
	"Tempest", "Zephyr",
	"Soarer", "Glider", "Diver", "Migrant",
	"Nester", "Chirper", "Hover", "Plumage",
	"Beak", "Wing",
	"Feather",
	"Claw",
	"Talon", "Beacon",
	"Singer", "Caller",
	"Flight", "Skyward",
	"Preen",
	"Bill",
	# Raptor-inspired:
	"Falcara", "Hawkwind", "Aquila",
	"Kestralis", "Ospryion",
	"Harrix", "Buzzaros",
	"Vultar", "Condrex", "Merlynx",

	# Songbirds-inspired:
	"Finchwind", "Larkspire", "Warblyn",
	"Thrushtar", "Sparrox", "Oriox", "Tanagral",
	"Chickador", "Wrenshade", "Nightinglare",

	# Waterfowl-inspired:
	"Duckshade", "Gooslyn",
	"Swanpeak",
	"Pintar", "Mallarion",
	"Tealis", "Pelicarn",
	"Heronshade", "Egryx",
	"Loonspire",

	# Ocean Birds-inspired:
	"Gullwind",
	"Terrix",
	"Albatrosar",
	"Puffinox",
	"Cormorantyx",
	"Petralis",
	"Skuarion",
	"Shearshade",

	# Tropical Birds-inspired:
	"Parroshade",
	"Macawind",
	"Toucanar",
	"Hoopion",
	"Sunbyrd",
	"Hornbillar",
	"Quetzyx",
	"Cotingar",

	# Game Birds-inspired:
	"Quailfire",
	"Pheasanar",
	"Grousewind",
	"Turkshade",
	"Guineaflare",
	"Peacox",
	"Ptarmyx",

	# Miscellaneous-inspired:
	"Owlspire",
	"Dovewind",
	"Pigeonyx",
	"Magpyre",
	"Jayshade",
	"Lyrebyrd",
	"Kiwix",
	"Pengshade",
	"Emurion",
	"Ostrix",
	"Cassowar",
	"Flamyn",
	"Cranar",
	"Storkwind",
	"Kingfisar",
	"Hummshade",
	"Woodpyre",
	"Ibix",
	"Tropicar"

	'Karawek',
	'Irnennatus',
	"Murder",
	"Corvid",
	"Corvus",
	"Cuervo",
	"Raven",
	"Murderfoe",
	"Corvo",
	"Crow",
	"Kraai",
	"Taruja",
	"Sorre",
	"Krahe",
	"Alghurab",
	"Agrrav",
	"Qarga",
	"KaKasi",
	"Kaka",
	"Varona",
	"Kyaeekaann",
	"Vrana",
	"Kaek",
	"Kage",
	"Corb",
	"Uwak",
	"Khwangwala",
	"Wuya",
	"Kaputa",
	"Kamagwi",
	"Corbu",
	"Kok",
	"Krage",
	"Kaalhu",
	"Cuervo",
	"Korbo",
	"Vares",
	"Belea",
	"Akpavia",
	"Varis",
	"Corbeau",
	"Feannag",
	"Fran",
	'Suzaku',
	'Havkov',
	'Sporr',
	'Novak',
	'Arrun',
	'Kakur',
	'Avilat',
	'Avin',
	'Aniv',
	'Vetum',
	'Rizati',
	'Falce',
	'Falcen',
	'Falcom',
	'Zaroil',
	'Gavilan',
	"Altantogos"
	"Kakem",
	"Artimisey",
	'Vetherse',
	'Condor',
		"Kakem",
		'Nova',
		'Elektraz',
		'Hawki',
		'Fahkumram',
		"Hawkili",
		'Cuco',
		'Master',
		"Sakurare",
		"Falcon",
		'Raven',
		"Raptorik",
		"Robin,"
		"Valkimes",
		"Avorig",
		"Robinhood",
		"Arkait",
		'Lentineicher',
		'Lantex',
		'Lenach',
		'Opurlio',
		"Kaka",
		"Kakasi",
		"Skyshriek",
		"Windwhisper",
		"Nighthawk",
		"Skygleam",
		"Stormwatch",
		"Raincry",
		"Snowplume",
		"Thundercaw",
		"Windfeather",
		"Songthief",
		"Eclipsing",
		"Shadowplay",
		"Sunshadow",
		"Pinnacle",
		"Crest",
		"Sable",
		"Flock",
		"Whistle",
		"Hush",
		"Lustrous",
		"Mottle",
		"Pepper",
		"Tint",
		"Hue",
		"Canvas",
		"Sketch",
		  "Inkfeather",
		  "Jewel",
		  "Gemwing",
		  "Prism",
		  "Spectra",
		  "Ripple",
		  "Glisten",
		  "Gleam",
		  "Harmony",
		  "Rhythm",
		  "Melody",
		  "Crescendo",
		  "Lilt",
		  "Aria",
		  "Sonnet",
		  "Verse",
		  "Chorus",
		  "Note",
		  "Chime",
		  "Bell",
		  "Tune",
		  "Clef",
		  "Lyric",
		  "Resonate",
		  "Hum",
		  "Whirl",
		  "Echoing",
		  "Tempest",
		  "Zephyr",
		  "Soarer",
		  "Glider",
		  "Diver",
		  "Albatrosar",
		  "Aquila",
		  "Beacon",
		  "Beak",
		  "Bill",
		  "Buzzaros",
		  "Caller",
		  "Chickador",
		  "Chirper",
		  "Claw",
		  "Condrex",
		  "Cormorantyx",
		  "Duckshade",
		  "Egryx",
		  "Falcara",
		  "Feather",
		  "Finchwind",
		  "Flight",
		  "Gooslyn",
		  "Gullwind",
		  "Harrix",
		  "Hawkwind",
		  "Heronshade",
		  "Hoopion",
		  "Hover",
		  "Kestralis",
		  "Larkspire",
		  "Loonspire",
		  "Macawind",
		  "Mallarion",
		  "Merlynx",
		  "Migrant",
		  "Nester",
		  "Nightinglare",
		  "Oriox",
		  "Ospryion",
		  "Parroshade",
		  "Pelicarn",
		  "Echoflap",
		  "Nestling",
		"Petralis",
		  "Pintar",
		  "Plumage",
		  "Preen",
		  "Puffinox",
		  "Shearshade",
		  "Singer",
		  "Skuarion",
		  "Skyward",
		  "Sparrox",
		  "Swanpeak",
		  "Talon",
		  "Tanagral",
		  "Tealis",
		  "Terrix",
		  "Thrushtar",
		  "Toucanar",
		  "Vultar",
		  "Warblyn",
		  "Wing",
		  "Wrenshade",
		  "Sunbyrd",
		  "Hornbillar",
		  "Quetzyx",
		  "Cotingar",
		  "Quailfire",
		  "Pheasanar",
		  "Grousewind",
		  "Turkshade",
		  "Guineaflare",
		  "Peacox",
		  "Ptarmyx",
		  "Owlspire",
		  "Dovewind",
		  "Pigeonyx",
		  "Magpyre",
		  "Jayshade",
		  "Lyrebyrd",
		  "Kiwix",
		  "Pengshade",
		  "Emurion",
		  "Ostrix",
		  "Cassowar",
		  "Flamyn",
		  "Cranar",
		  "Storkwind",
		  "Kingfisar",
		  "Hummshade",
		  "Woodpyre",
		  "Ibix",
		  "Tropicar",

		  "Skyward",
		  "Kamagwi",
		  "Kaputa",
		  "Khwangwala",
		  "Kok",
		  "Korbo",
		  "Krage",
		  "Krahe",
		  "Kyaeekaann",
		  "Mimic",
		  "Plume",
		  "Qarga",
		  "Shimmer",
		  "Sorre",
		  "Talon",
		  "Taruja",
		  "Uwak",
		  "Vares",
		  "Varis",
		  "Varona",
		  "Vrana",
		  "Wuya",
		  "Ovicos",
		  "Soar",
		  "Shade",
		  "Dusk",
		  "Dawn",
		  "Twilight",
		  "Nightcall",
		  "Wingbeat",
		  "Rustle",
		  "Murmur",
		  "Feather",
		  "Perch",
		  "Roost",
		  "Glitter",
		  "Beaksharp",
		  "Swoop",
		  "Windrider",
		  "Cloudwing",
		  "Skydance",
		  "Mooncaw",
		  "Sunfeather",
		  "Starshine",
		  "Hoopoe",
		  "Chatter",
		  "Squawk",
		  "Preen",
		  "Beacon",
		  "Ruffle",
		  "Silhouette",
		  "Frostwing",

		"Storm",
		"Jaria",
		"Jark",
		"Jara",
		"Jars",
		  "Agrrav",
		  "Akpavia",
		  "Alghurab",
		  "Belea",
		  "Corb",
		  "Corbeau",
		  "Corbu",
		  "Cuervo",
		  "Echo",
		  "Feannag",
		  "Flit",
		  "Fran",
		  "Glide",
		  "Kaalhu",
		  "Kaek",
		  "Kage",

		]
	if "Kenku" in genus:
		Names += [
		'Fíac',"Murder",
		"Corvo",
		"Kheree", "Choak",
		"Kavala",
		"Kaokao", "Cawla",
		"Caw", "Goaika",
		"Gagak", "Kakka",
		"Vrana", "Kraischen",
		"Nnamungoona", "Libata",
		"Varna", "Fung",
		"Zax", "Blak", "Bod",
		"Black", "Karga",
		"Igikona",
		"Qarga", "Manuk",
		"Gagak",
		"Karasu", "Corvo",
		"Kraka", "Preachan",
		"Crow",
		"Raven",
		"Rook",
		"Corax", "Burung",
		"Gagak",
		"Uwak", "Uko",
		"Varju",
		"Tsov",
		"Kaua",
		"Koo", "Hankaka",
		"Kagado", "Yryvu",
		"Koraki", "Qvavi",
		"Kaga", "Krake",
		"Qurruu",
		"Kam", "Wrona",
		"Corvo", "Cuervo",
		"Cioara", "Vorona",
		"Matuu", "Legokobu",
		"Vrana",
		"Lekgwaba", "Gunguwo",
		"Tuke",
		"Kunguru", "Gala",
		"Gagak", "Uwak", "Xika",
		"Kakam", "Kapra", "Zoq", "Kaki",
		"Vukuvuku", "Karga",
		"Garga", "Kwaakwaadabi",
		"Vorona", "Qarga", "Conqua",
		"Unomyayi", "Krou",
		"Kuroo", "Igwababa", "Kror",
		"Kak", "Kakab",
		"Kargw", "Kri",
		"Karok", "Corak",
		"Kavue", "Kakur",
		"Karaga",
		"Kakor", "Kaerv",
		"Kagaka",
		"Comunko",
		"Corv", "Krueng",
		"Karak",
		"Kalaa",
		"Cabur",
		"Kara", "Kak",
		"Karvis", "Korvun",
		"Corvi", "Kukurv",
		"Haden", "Kanak", "Lera",
		"Krai", "Kabak",
		"Unkur", "Kagan",
		"Kakur", "Krara",
		"Koror", "Kakara",
		"Kar",
		"Kaa", "Corr",
		"Kavon", "Kanaka",
		"Kakut", "Kakak",
		"Kax",
		"Koke",
		"Kaeru",
		"Karva",
		"Covar",
		"Karu",
		"Kakar",
		"Kana",
		"Kav",
		"Draven",
		"Kenku",
		"Chirrik",
		"Corvid",
		"Corvus",
		"Cuervo",
		"Raven",
		"Murderfoe",
		"Corvo",
		"Crow",
		"Kraai",
		"Taruja",
		"Sorre",
		"Krahe",
		"Alghurab",
		"Agrrav",
		"Qarga",
		"KaKasi",
		"Kaka",
		"Varona",
		"Kyaeekaann",
		"Vrana",
		"Kaek",
		"Kage",
		"Corb",
		"Uwak",
		"Khwangwala",
		"Wuya",
		"Kaputa",
		"Kamagwi",
		"Corbu",
		"Kok",
		"Krage",
		"Kaalhu",
		"Cuervo",
		"Korbo",
		"Vares",
		"Belea",
		"Akpavia",
		"Varis",
		"Corbeau",
		"Feannag",
		"Fran",
		"Frank",
		'Roek',
		'Karasu',
		'Hosa',
		'Branoc',
		'Corbin',
		'Hrokr',
		'Soua',
		'Koa',
		'Kalag',
		'Teutobod',
		'Okohkeso',
		'Korak',
		'Kalas',
		'Kangee',
		'Branwen',
		'Sycorax',
		'Fiachna',
		'Angilram',
		'Krakr',
		'Kurak',
		'Niaowu',
		'Hrafnhildr',
		'Engilram',
		'Tulugaq',
		'Hraban',
		'Tjorven',
		'Okohkeveho',
		'Hrafn',
		'Voron',
		'Okohkevo',
		'Korbinian',
		'Wanwu',
		'Omaestse',
		'Raven',
		'Baldram',
		'Hrambert',
		'Féchín',
		'Biliram',
		'Wolfram',
		'Fiachra',
		'Kuzgun',
		'Heilram',
		'Fiachrae',
		'Blaeingr',
		'Brandubh',
		'Rabe',
		'Harafantyir',
		'Harafanfifa',
		'Fiach',
		'Corvus',
		'Fiacha',
		'Cynfran',
		'Fiech',
		'Dindrane',
		'Folcram',
		'Dulcedram',
		'Heimram',
		'Ransley',
		'Remmelt',
		'Sindram',
		'Walaram',
		'Rambald',
		'Liutram',
		'Inghiramo',
		'Hrafngerthur',
		'Hollo',
		'Hosa',
		'Joceran',
		'Hrafnheithur',
		'Hraefn',
		'Kalas',
		'Hrafnkell',
		'Hrafndís',
		'Soua',
		'Rotram',
		'Ranulf',
		'Walderam',
		'Kohkahycumest',
		'Rauke',
		'Salaram',
		'Ramfrid',
		'Nokka',
		'Stolas',
		'Wanwu',
		'Ramtrud',
		'Oreb',
		'Theuderam',
		'Sicleramna',
		'Ravna',
		'Wigram',
		'Tsio',
		'Remaclus',
		'Ramund',
		'Otran',
		'Wilfram',
		'Xhuuyaa',
		'Williram',
		'Voron',
		'Kwaris',
		'Sigram',
		'Remme',
		'Ranne',
		'Ramward',
		'Quikinna',
		'Krakr',
		'Karasu',
		'Harafentina'
		'Hrafney',
		'Gagi',
		'Emmeram',
		'Brangen',
		'Guntram',
		'Roan',
		'Brennus',
		'Orthros',
		'Nokka',
		'Karasu',
		'Gargabay',
		'Koyah',
		'Alaram',
		'Bertram',
		'Bran',
		'Fala',
		'Fainche',
		'Korpor',
		'Adalram',
		'Berahthraban',
		'Bran',
		'Cynfran',
		'Cathubodua',
		'Bugafer',
		'Branoc',
		'Boduognatos',
		'Beila',
		'Badeb',
		'Angwusnasomtaqa',
		'Algorab',
		'Mekaisto',
		'Muxika',
		'Isapo',
		'Crawford',
		'Vasco',
		'Rocco',
		'Koronis',
		"Corvid",
		"Corvus",
		"Cuervo",
		"Corvo",
		"Choak",
		"Kheree",
		"Murder",
		"Murderfoe",
		"Raven",
		"Corvo",
		"Crow",
		"Kraai",

		"Kavala",
		"Kaokao",
		"Cawla",
		"Caw",
		"Goaika",
		"Gagak",
		"Kakka",
		"Vrana",
		"Kraischen",
		"Nnamungoona",
		"Libata",
		"Varna",
		"Fung",
		"Zax",
		"Blak",
		"Bod",
		"Black",
		"Karga",
		"Igikona",
		"Qarga",
		"Manuk",
		"Gagak",
		"Karasu",
		"Corvo",
		"Kraka",
		"Preachan",
		"Crow",
		"Raven",
		"Rook",
		"Corax",
		"Burung",
		"Gagak",
		"Uwak",
		"Uko",
		"Varju",
		"Tsov",
		"Kaua",
		"Koo",
		"Hankaka",
		"Kagado",
		"Yryvu",
		"Koraki",
		"Qvavi",
		"Kaga",
		"Krake",
		"Qurruu",
		"Kam",
		"Wrona",
		"Corvo",
		"Cuervo",
		"Cioara",
		"Vorona",
		"Matuu",
		"Legokobu",
		"Vrana",
		"Lekgwaba",
		"Gunguwo",
		"Tuke",
		"Kunguru",
		"Gala",
		"Gagak",
		"Uwak",
		"Xika",
		"Kakam",
		"Kapra", "Zoq",
		"Kaki",
		"Vukuvuku",
		"Karga",
		"Garga",
		"Kwaakwaadabi",
		"Vorona",
		"Qarga",
		"Conqua",
		"Unomyayi",
		"Krou",
		"Kuroo",
		"Igwababa",
		"Kror",
		"Kak",
		"Kakab",
		"Kargw",
		"Kri",
		"Karok",
		"Corak",
		"Kavue",
		"Kakur",
		"Karaga",
		"Kakor",
		"Kaerv",
		"Kagaka",
		"Comunko",
		"Corv",
		"Krueng",
		"Karak",
		"Kalaa",
		"Cabur",
		"Kara",
		"Kak",
		"Karvis",
		"Korvun",
		"Corvi",
		"Kukurv",
		"Haden",
		"Kanak",
		"Lera",
		"Krai",
		"Kabak",
		"Unkur",
		"Kagan",
		"Kakur",
		"Krara",
		"Koror",
		"Kakara",
		"Kar",
		"Kaa",
		"Corr",
		"Kavon",
		"Kanaka",
		"Kakut",
		"Kakak",
		"Kax",
		"Koke",
		"Kaeru",
		"Karva",
		"Covar",
		"Karu",
		"Kakar",
		"Kana",
		"Kav",
		"Draven",
		"Kenku",
		"Chirrik",
		]

	if "Owlin" in genus:
		Names += [
		"Ookag",
		]

	if FEMALE:
		Names += [
		'Ayuko',
		'Venus',
		'Nauja',
		'Yaen',
		'Curca',
		'Dindonette',
		'Kunagadoga',
		'Luv',
		'Chaurisse',
		'Suzume',
		'Meique',
		'Nascha',
		]

	if MALE:
		Names += [
		'Kele',
		'Torgay',
		'Otos',
		'Mongwau',
		'Bashukat',
		'Dianoz',
		'Kanagatucko',
		'Wuyi',
		'Xiuhcozcatl',
		'Ampush',
		'Azio',
		'Bumin',
		'Kuzco',
		'Mupitsukupu',
		'Caligo',
		'Chichatlapal',
		'Cuauhtecolotl',
		'Ibid',
		'Jarli',
		'Kotori',
		]

	return Names

def Surnames(genus):
	return Names(genus)

def Phonotactic(genus):
	onset  = [""]
	nuclei = [""]
	codas  = [""]
	onset +=  ['Hawk','Rapt','Av', 'Falc','Sanw', 'Esp', 'Crow','Eagl',
		"Col", 'Tuc', 'Lor']
	nuclei += ['or','ic','in','inj','ecr','','','','','arr', 'ibr']
	codas +=  ['in','i','e','on','ay','ow','a', 'an']
	return onset, nuclei, codas

def Surphonotactic(genus):
	onset  = [""]
	nuclei = [""]
	codas  = [""]
	return onset, nuclei, codas
