
'''
Devils (Freudian Perspective):
	Superego Dominance: Devils embody the superego aspect of Freud's psychoanalytic theory. They represent strict adherence to moral codes, self-punishment, and retribution for transgressions.
	Guilt and Punishment: Devils thrive on guilt and punish those who deviate from societal or personal moral standards. They may manipulate individuals into feeling guilty for their actions and then exact punishments accordingly.
	Hierarchy and Order: Devils often operate within a structured hierarchy, with powerful archdevils at the top enforcing strict rules and punishments. They may seek to impose order and control over chaotic forces.
	Deals for Power and Control:
		Devils offer individuals the opportunity to fulfill their ambitions and desires in exchange for allegiance or service. This could involve granting political influence, magical abilities, or material wealth.
		They manipulate mortals by playing on their desires for dominance and control over others, promising them the means to achieve their goals in exchange for obedience.
		Temptation and Redemption: Devils may tempt individuals with promises of redemption or absolution in exchange for servitude or acts of penance.
		However, their ultimate goal is to maintain control through fear and guilt.
	Contracts with Consequences:
		Devils craft intricate contracts with hidden clauses and consequences, exploiting loopholes to ensure the individual's continued servitude or suffering.
		Individuals may initially be enticed by the immediate benefits of the deal, but eventually realize the true cost of their pact as they become ensnared in the Devil's web of manipulation.
	Illusions of Grandeur:
		Devils create illusions of grandeur and false promises of greatness, leading individuals to believe they can rise above their limitations and achieve ultimate power.
		However, these illusions often lead to downfall, as individuals become consumed by their own ambition and the Devil's influence.
		The allure of power can lead individuals to compromise their ethical principles and engage in behavior they would have previously considered unacceptable.
		As individuals wield power, they may become desensitized to the consequences of their actions, leading to a diminished sense of guilt and remorse.
		Power can inflate individuals' egos and foster a sense of superiority and entitlement, akin to Freud's concept of narcissism.
		Individuals may come to believe they are above moral reproach, justifying their actions through rationalizations and self-serving interpretations.
		Those who attain significant power may seek to exert control over others, imposing their will and beliefs on society.
		This authoritarian behavior can reflect an imbalance between the individual's ego and superego, with the ego prioritizing its own desires for dominance and control over ethical considerations.
	Manipulation through Fear and Guilt:
		While Devils may not offer redemption outright, they exploit individuals' fears and guilt to coerce them into making deals. They prey on insecurities and weaknesses, manipulating emotions to their advantage.
'''
'''
Demons (Jungian Perspective):
	Internal struggle with temptation and the allure of indulgence.
	Id Dominance: Demons epitomize the id aspect of Jung's psychoanalytic theory. They embody raw primal urges, unchecked impulses, and unrestrained desires.
	Chaos and Destruction: Demons revel in chaos and destruction. They may incite conflict, indulgence, and hedonism wherever they go.
	Ego Dissolution: Demons seek to dissolve the ego and unleash the primal instincts buried within individuals. They may tempt mortals with promises of immediate gratification, feeding off their desires and egotistical pursuits.
	Anarchy and Disarray: Demons eschew hierarchical structures and thrive in environments of anarchy and disarray. They resist order and seek to dismantle societal norms, embracing entropy and discord.
	Corruption of the True Self:
		Demons embody the darker aspects of individuals' psyches, amplifying their primal instincts and desires to the point of corruption.
		They tempt mortals to indulge in their deepest desires, promising liberation from societal constraints and the fulfillment of their innermost cravings.
	Inherent Corruption:
		Demons thrive on the inherent chaos and darkness within mortals, seeking to unleash and magnify these latent impulses.
		By seducing individuals into embracing their base instincts, Demons facilitate the erosion of moral boundaries and the corruption of the soul.
	Incitement of Hedonism and Indulgence:
		Demons revel in hedonism and excess, encouraging mortals to pursue pleasure and gratification without regard for consequences.
		They incite indulgence in sinful pleasures, leading individuals down a path of self-destruction and moral decay.
	Subversion of Will and Autonomy:
		Demons subvert individuals' willpower and autonomy, exploiting weaknesses and vulnerabilities to manipulate them into serving their own nefarious purposes.
		Through deceit and temptation, Demons ensnare mortals in a cycle of desire and despair, trapping them in a downward spiral of corruption.
'''

'''
Names for Fiends
Inspirations
	- Demonology
	- Demons (Meaning)

'''


def Names(Type):
	MALE    = "He"    in Type
	FEMALE  = "She"   in Type
	AGENDER = "They"  in Type

	SUBTYPE =   "Subtype" in Type
	TIEFLING =  "Tiefling" in Type

	Virtue_Names = [
"Disaster",
"Strong",
"Forte",
"Glory",
"Hawk",
"Falcon",
"Sinner",
"Dawn",
"Crepusculo",
"Flama",
"Flame",
"Sunrise",
"Alba",
"Star",
"Estrella",
"Estela",
"Legend",
"Blood",
"Aeon",
"Veil",
"Victor",
"Victoria",
"Honor",
"Noble",
"Ley",
"Law",
"Melody",
"Purity",
"Rune",
"Ron",
"Gin",
"Sinfinder",
"Sinner",
"Song",
"Cult",
"Culto",
"Prayer",
"Pray",
"Gunner",
"Katana",
"Jester",
"King", 	"Ambition",
"Art", 	"Chant",
"Canto",
"Creed",
"Death",
"Despair",
"Doom",
"Doubt",
"Dread",
"Ecstasy", 	"Entropy",
	"Excellence",
	"Fear",

	"Miedo",

	"Glory",
	"Gloria",
	"Gluttony",
	"Grief",

	"Hate",
	"Hope",
	"Horror",

	"Ideal", 	"Amor",

		"Crimson",
		"Caos", 	"Grace",

			"Liberty",
			"Luz", 	"Lust",
				"Love",

				"Mayhem",
				"Mockery",
				"Murder",
				"Muse",
				"Musa",
				"Music",
				"Mystery",	"Nowhere",

					"Open",

					"Piety",
					"Pain",
					"Passion",
					"Poetry",

					"Quest", 	"Random",
						"Reverence",
						"Revulsion",
						"Risa", 	"Sorrow",	"Temerity",
								"Torment",
								"Tragedy",	"Vice",
									"Virtue",	"Weary",
										"Wit",

		"Hope",
		"Valor",
		"Mystery",
		"Quiet",
		"Song",
		"Charm",
		"Glimmer",
		"Glory",
		"Noble",
		"Lumin",
		"Whisper",
		"Dancer",
		"Mirth",
		"Revel",
		"Wry",
		"Prayer",
		"Pursuit",
		"Promise",
		"Sorrow",
		"Chance",
		"Eager",
		"Endure",
		"Hallow",
		"Luster",
		"Mend",
		"Riddle",
		"Shade",
		"Wander",
		"Penance",
		"Dream",
		"Serenity",
		"Bliss",
		"Fury",
		"Glee",
		"Insight",
		"Seeker",
		"Solemn",
		"Fate",
		"Grace",
		"Truth",
		"Honor",
		"Vigor",
		"Rapture",
		"Zeal",
		"Oath",
		"Radiant",
		"Sacred",
		"Bravery",
		"Cunning",
		"Defiance",
		"Elude",
		"Freedom",
		"Justice",
		"Mercy",
		"Temperance",
		"Trust",
		"Victory",
		"Vow",
		"Watch",
		"Will",
		"Silent",
		"Solace",
		"Subtle",
		"Thrift",
		"Vivid",
		"Abyss",
		"Serene",
		"Blaze",
		"Glimmer",
		"Torment",
		"Comfort",
		"Wrath",
		"Calm",
		"Venom",
		"Elixir",
		"Malice",
		"Grace",
		"Ravage",
		"Mend",
		"Deceit",
		"Truth",
		"Vile",
		"Pure",
		"Treachery",
		"Loyal",
		"Gloom",
		"Radiance",
		"Dread",
		"Hope",
		"Spite",
		"Favor",
		"Chaos",
		"Order",
		"Ruin",
		"Preserve",
		"Fury",
		"Peace",
		"Woe",
		"Bliss",
		"Taint",
		"Wholesome",
		"Cruel",
		"Kind",
		"Envy",
		"Cherish",
		"Despair",
		"Optimism",
		"Scream",
		"Whisper",
		"Bane",
		"Blessing",
		"Strife",
		"Unity",
		"Haunt",
		"Guard",
		"Sin",
		"Merit",
		"Curse",
		"Gift",
		"Hate",
		"Love",
		"Thorn",
		"Bloom",
		"Shadow",
		"Light",
		"Scorch",
		"Soothe",
		"Rage",
		"Temperance",
		"Grieve",
		"Joy",
		"Decay",
		"Nourish",
		"Lust",
		"Devotion",
		"Pride",
		"Humble",
		"Greed",
		"Generosity",
		"Lies",
		"Honesty"
		"Zephyron",
		"Draconar",
		"Typhos",
		"Venox",
		"Grisham",
		"Blazefur",
		"Sulfuron",
		"Vornak",
		"Ildrex",
		"Mortigon",
		"Firesyl",
		"Lilivra",
		"Mornara",
		"Shadeveil",
		"Nefari",
		"Blazelle",
		"Sorcaria",
		"Vexiana",
		"Glimshade",
		"Vorrela",
		"Raventhorn",
		"Skullrend",
		"Shadowclaw",
		"Doomspire",
		"Felrend",
		"Horrorspire",
		"Nighthowl",
		"Vileshade",
		"Hexmorn",
		"Darkgleam",
		"Hellkin",
		"Nightshade",
		"Doombringer",
		"Ashcaller",
		"Soulbinder",
		"Fireheart",
		"Demonblood",
		"Sinwhisperer",
		"Darkmender",
		"Brimstonetouched",
		"Kurzam",
		"Rhul",
		"Zorlarg",
		"Steamsable",
		"Onyxmaw",
		"Kral",
		"Moltenhorn",
		"Crimsonhorn",
		"Gloomhorn",
		"Madhorn",
		"Killsin",
		"Purific",
		"Nye",
		"Assurance",
		"Watson",
		"Faith",
		"Harris",
		"Ashes",
		"Shepard",
		"Tenacious",
		"Coleman",
		"Desire",
		"Llwyd",
		"Vanity",
		"Temple",
		"Submit",
		"French",
		"Fear",
		"Reynolds",
		"Wheelwright",
		"Called",
		"Burroughs",
		"Confidence",
		"Udal",
		"Remember",
		"Bond",
		"Recuerdo",
		"Miedo",
		"Obedience",
		"Young",
		"Faint",
		"Gilby",
		"Abuse",
		"Cawdrey",
		"Constant",
		"Calamy",
		"Calamidad",
		"Vanity",
		"Twisse",
		"Discretion",
		"Boston",
		"Buried",
		"Sampson",
		"Hateill",
		"Burton",
		"Forsaken",
		"Williams",
		"Virtue",
		"Shepard",
		"Amynus",
		"Smen",
		"Apronadius",
		"Abdamelek",
		"Xonsu",
		"Aziza",
		"Ramla",
		"Neema",
		"Cleopatra",
		"Jendayi",
		"At",
		"Sahura",
		"Hor",
		"Zesiro",
		"Nub",
		"Bubastis",
		"Tauret",
		"Sarapous",
		"Ma",
		"Sapt",
		"Ritho",
		"Nenet",
		"Sanura",
		"Sethenes",
		"Sept",
		"Uetu",
		"Kashto",
		"Clémence",
		"Firefur",
		"Gloomtail",
		"Nuuch",
		"Zenglac",
		"Ablo",
		"Gadreel",
		"Uzza",
		"Musique",
		"Haine",
		"Gloire",
		"Pyra",
		"Désespoir",
		"Doute",
		"Chagrin",
		"Terreur",
		"Ambition",
		"Vice",
		"Ouverture", "Amour",
		"Témérité", "Credo",
		"Charogne",
		"Chagrin",
		"Hasard",
		"Astaro", "Kali",
		"Brave",
		"Crash",
		"Delver",
		"Helm",
		"Hungry",
		"Violence",
		"Providence",
		"Surprise", "Conqueror",
		"Defender", "Invader",
		"Juvileo",

		'Faithful',
		'Aali',
		'Aaliyah',
		'Abrar',
		'Acacius',
		'Adalet',
		'Adela',
		'Justus',
		'Justice',
		'Noble',
		'Adila',
		'Adil',
		'Agamemnon',
		'Agaue',
		'Ahava',
		'Ai',
		'Aitor',
		'Aki',
		'Akram',
		'Alaia',
		'Alethea',
		'Alheri',
		'Aliza',
		'Amaal',
		'Amandeep',
		'Amarachi',
		'Amatus',
		'Ami',
		'Amice',
		'Amika',
		'Amin',
		'Amista',
		'Amity',
		'Anargyros',
		'Anis',
		'Honora',
		'Ardito',
		'Ari',
		'Arman',
		'Augustos',
		'Benignus',
		'Caridad',
		'Charity',
		'Clemency',
		'Concordia',
		'Constancia',
		'Constantine',
		'Dharma',
		'Enoch',
		'Eskarne',
		'Esperanta',
		'Faith',
		'Generosus',
		'Felicity',
		'Glory',
		'Grace',
		'Judas',
		'Harmony',
		'Honor',
		'Hope',
		'Itxaro',
		'Joy',
		'Justus',
		'Love','Mercy',
		'Peace',
		'Pax',
		'Tadashi',
		'Tahir',
		'Temperance',

			"Haunt",
			"Cruel",
			"Cult",
			"Culto",
			"Curse",
			"Decay",
			"Curson",
			"Dawn",
			"Crash",
			"Credo",
			"Creed",
			"Crepusculo",
			"Criella",
			"Calamy",
			"Calder",
			"Crimson",
			"Crimhorn",
			"Disaster",
			"Discretion",
			"Doom",
			"Desire",
			"Despair",
			"Despair",
			"Doombringer",
			"Doomspire",
			"Doubt",
			"Devotion",
			"Cherish",
			"Cimer",
			"Cimeries",
			"Excellence",
			"Dread",
			"Dread",
			"Désespoir",
			"Estela",
			"Estrella",
			"Entropy",
			"Envy",
			"Furia",
			"Fury",
			"Fury",
			"Generosity",
			"Gift",
			"Ecstasy",
			"Faint",
			"Faith",
			"Favor",
			"Fear",
			"Fear",
			"Firefur",
			"Fireheart",
			"Firesyl",
			"Flama",
			"Flame",


			"Falcon",

			"Horror",
			"Horrorspire",
			"Humble",
			"Honesty"
			"Honor",
			"Hope",
			"Hope",
			"Death",
			"Hate",
			"Odio",
			"Guard",
			"Ill",
			"Gloom",
			"Grace",
			"Grace",
			"Gin",
			"Glimmer",
			"Glimshade",
			"Gloire",
			"Gloomhorn",
			"Gloomtail",
			"Gloria",
			"Glory",
			"Glory",
			"Gluttony",
			"Greed",
			"Grief",
			"Grieve",
			"Grisham",
			"Gunner",

			"Huya",
			"Hungry",
			"Ron",
			"Law",
			"Legend",
			"Legion",
			"Invader",
			"Jester",
			"Ideal",
			"Juvileo",
			"Killsin",
			"Kind",
			"King",

			"Obedience",
			"Nowhere",
			"Malice",
			"Luz",
			"Ley",
			"Liberty",
			"Lies",
			"Light",
			"Lux",

			"Noble",
			"Miedo",
			"Miedo",
			"Mockery",

			"Rum",
			"Ruin",
			"Rune",
			"Passion",
			"Open",
			"Optimism",
			"Order",
			"Ouverture",
			"Pain",
			"Pyra",
			"Pyra",
			"Quest",
			"Quiet",

			"Random",
			"Piety",
			"Poetry",
			"Peace",
			"Pray",
			"Prayer",
			"Preserve",
			"Pride",
			"Pride",
			"Providence",
			"Pura",
			"Pure",
			"Purific",
			"Purity",
			"Radiance",
			"Rage",

			"Lust",
			"Lust",
			"Canto",
			"Caos",
			"Recuerdo",
			"Remember",
			"Reverence",
			"Revulsion",
			"Danza",
			"Darkgleam",
			"Darkmender",
			"Chant",
			"Chaos",
			"Santeria",
			"Sanura",
			"Sapt",
			"Scepter",
			"Scorch",
			"Scream",
			"Shadow",
			"Sinner",
			"Sinner",
			"Sinwhisperer",
			"Called",
			"Song",
			"Soothe",
			"Sunrise",
			"Salt",
			"Calm",
			"Crowley",
			"Elixir",
			"Sorrow",
			"Spite",
			"Star",
			"Steamsable",
			"Strife",
			"Strong",
			"Submit",
			"Subtle",
			"Murder",
			"Murmur",
			"Musa",
			"Muse",
			"Music",
			"Musique",
			"Mystery",
			"Nemesis",
			"Buried",
			"Burroughs",
			"Burton",

			"Soulbinder",
			"Solace",
			"Shepard",
			"Shepard",
			"Silent",
			"Sin",
			"Sinfinder",
			"Unity",
			"Temerite",
			"Temerity",
			"Torment",
			"Torment",
			"Tragedy",
			"Treachery",
			"Truth",
			"Thorn",
			"Thrift",
			"Love",
			"Love",
			"Loyal",
			"Surprise",
			"Defender",
			"Delver",
			"Demonblood",

			"Vanity",
			"Vanity",
			"Veil",
			"Venom",
			"Vice",
			"Vice",
			"Victor",
			"Victoria",
			"Vile",
			"Vileshade",
			"Vine",
			"Violence",
			"Virtue",
			"Virtues",
			"Vivid",
			"Bond",
			"Wander",
			"Ashcaller",
			"Ashes",
			"Assurance",
			"Bane",
			"Blaze",
			"Blazefur",
			"Blazelle",
			"Blessing",
			"Bliss",
			"Bliss",
			"Blood",
			"Bloom",
			"Forsaken",
			"Forte",
			"Fortea",
			"Warren",
			"Amen",
			"Amor",
			"Amour",
			"Art",
			"Brave",
			"Cabala",
			"Watch",
			"Watson",
			"Weary",
			"Wright",
			"Ignominy",
			"Whisper",
			"Whisper",
			"Wholesome",
			"Wit",
			"Ravage",
			"Woe",
			"Wrath",
			"Merit",
			"Merit",
			"William",
			"Iam",
			"Will",
			"Hate",
			"Hate",
			"Bravery",
			"Chance",
			"Change",
			"Charm",
			"Cunning",
			"Dancer",
			"Deceit",
			"Defiance",
			"Dream",
			"Eager",
			"Elude",
			"Endure",
			"Fate",
			"Freedom",
			"Fury",
			"Glee",
			"Glimmer",
			"Glory",
			"Grace",
			"Hallow",
			"Honor",
			"Hope",
			"Insight",
			"Juramenta",
			"Juramento",
			"Justice",
			"Luster",
			"Nightshade",
			"Night",
			"Alba",
			"Vow",
			"Vigor",
			"Victory",
			"Valor",
			"Truth",
			"Trust",
			"Temperance",
			"Sorrow",
			"Comfort",
			"Confidence",
			"Conqueror",
			"Constant",
			"Constantine",
			"Song",
			"Radiant",
			"Rapture",
			"Revel",
			"Riddle",
			"Ambition",
			"Ambition",
			"Sacred",
			"Seeker",
			"Serenity",
			"Shade",
			"Solemn",
			"Mend",
			"Mercy",
			"Mystery",
			"Noble",
			"Oath",
			"Oath",
			"Penance",
			"Prayer",
			"Promise",
			"Chivalry",

			"Pursuit",
			"Blade",
			"Blaze",

			"Young",
			"Calamidad",
			"Calamity",
		]
	Fiend_Names = [
	'Atlianorm',"Nephelin", 'Mephistopheles', 'Mefistofeles',	"Nefelin", "Serafina",	"Luz", "Carolin",	"Dilan", "Kurt",	"Freddie", "Pride", "Bulur",	"Abyx", "Apolion",	"Abezetibou", "Abigor",	"Abraxas", "Abraxis",	"Solomon", "Aexma",	"Acaos",	"Adramalek",	"Agares",	"Ariman",	"Agraz",	"Ainin",	"Alloces",	"Alp",	"Amduscias",	"Amenadiel",	"Amon",	"Amorth",	"Gabriele",	"Andra",	"Indra",	"Andras",	"Andrealfus",	"Mastemoth",	"Andromalius",	"Angra",	"Antaura",	"Antichrist",	"Antichristian",	"Armadiel",	"Aseliel",	"Asmodeus",	"Aeshma",	"Ashmedai",	"Asmodius",	"Sydonay",	"Astaroth",	"Azael",	"Azazel",	"Baal",	"Bael",	"Balam",	"Baphomet",	"Bafomet",	"Barbiel",	"Barbuel",	"Barmiel",	"Baruchas",	"Bathin",	"Barbatos",	"Beelxebub",	"Belzebub",	"Satan",	"Ornias",	"Nicodemus",	"Behemoth",	"Lucifer",	"Madilon",	"Solymo",	"Saroy",	"Zeu",	"Ameclo",	"Sagrael",	"Praredun",
	"Venite",
	"Amen",
	"Leviatan",
	"Beherit",
	"Belet",
	"Bilet",
	"Belfegor",
	"Belial",
	"Beliar",
	"Bernael",
	"Bidiel",
	"Beriz",
	"Balberiz",
	"Beal",
	"Bofi",
	"Bolfri",
	"Elberiz",
	"Bidiel",
	"Bifrons",
	"Botis",
	"Otis",
	"Buer",
	"Buriel",
	"Busyasta",
	"Cabariel",
	"Calder",
	"Camuel",
	"Caim",
	"Camion",
	"Carnesiel",
	"Caspiel",
	"Cassian",
	"Kerberos",
	"Cerberus",
	"Cesmak",
	"Coronzon",
	"Cimeries",
	"Constantine",
	"Crowley",
	"Daeva",
	"Deva",
	"Dev",
	"Daimon",
	"Agato",
	"Agatodaimon",
	"Kako",
	"Kakodaimon",
	"Dalkiel",
	"Dantanian",
	"Decarabia",
	"Carabia",
	"Demoriel",
	"Faustus",
	"Eligor",
	"Emoniel",
	"Erinyes",
	"Fury",
	"Furia",
	"Eurynomus",
	"Forneus",
	"Fortea",
	"Flauros",
	"Hauras",
	"Haurus",
	"Foras",
	"Furcas",
	"Furfur",
	"Gadreel",
	"Gadriel", "Garadriel",
	"Gediel", "Gemori",
	"Gamaliel", "Gamigin",
	"Solomon", "Gusion",
	"Hades",
	"Hagenti",
	"Harlequin",
	"Halahel",
	"Halpas",
	"Hecataea",
	"Hel",
	"Hemah",
	"Hutriel",
	"Iblis",
	"Icosiel",
	"Incubus",
	"Imp",
	"Ipos",
	"Isacaron",
	"Leviatan",
	"Cabala",
	"Sephirot",
	"Sefirot",
	"Kezer",
	"Kokmah",
	"Binah",
	"Kesed",
	"Geburah",
	"Tifarez",
	"Netzak",
	"Hod",
	"Yesod",
	"Malkut",
	"Kababiel",
	"Kesilim",
	"Kunda",
	"Kabiel",
	"Kokab",
	"Labartu",
	"Lahmu",
	"Lamastu",
	"Legion",
	"Lerajie",
	"Oary",
	"Leviatan",
	"Liliz",
	"Lucifer",
	"Luzer",
	"Lutin",
	"Macariel",
	"Malgaras",
	"Malphas",
	"Malpas",
	"Marbas",
	"Maseriel",
	"Mazaquin",
	"Mazzikin",
	"Mazikin",
	"Mazakin",
	"Menadiel",
	"Mefistofeles",
	"Moloch",
	"Morax",
	"Murmur",
	"Naberius",
	"Nephilim",
	"Nefilim",
	"Nemesis",
	"Nisroc",
	"Onoskelis",
	"Orias",
	"Ornias",
	"Orobas",
	"Ose",
	"Padiel",
	"Pamersiel",
	"Paimon",
	"Pairikas",
	"Pazuzu",
	"Santeria",
	"Purson",
	"Curson",
	"Rabisu",
	"Raum",
	"Ravana",
	"Raysiel",
	"Rimmon",
	"Ronove",
	"Roneve",
	"Sabbat",
	"Sabnak",
	"Salem",
	"Saleos",
	"Salt",
	"Samael",
	"Sammael",
	"Sariel",
	"Sarakiel",
	"Suriel",
	"Uriel",
	"Zerakiel",
	"Satanael",
	"Scepter",
	"Skepter",
	"Shamsiel",
	"Shax",
	"Chax",
	"Scox",
	"Shedim",
	"Sinistrari",
	"Lodovico",
	"Sitri",
	"Orleans",
	"Surin",
	"Symiel",
	"Taru",
	"Tase",
	"Teofilus",
	"Udug",
	"Ukobach",
	"Usiel",
	"Uziel",
	"Uzza",
	"Uriel",
	"Valac",
	"Valefor",
	"Vapula",
	"Vassago",
	"Veltis",
	"Vepar",
	"Separ",
	"Vine",
	"Warren",
	"Zaffis",
	"Zarika",
	"Zepar",
	"Zohk",
	"Zoroastra",
	"Zohak",

	"Dante",
	"Danza",
	"Apocalypse",
	"Astaroz",
	"Astaroth",
	"Khemed",
	"Ahset",
	"Amunet",
	"Aneksi",
	"Atet", "Baketamon",
	"Bunefer",
	"Hentie",
	"Herit",
	"Heteferes",
	"Ipuet",
	"Itet",
	"Joba",
	"Kasmut",
	"Kemanub",
	"Khemut",
	"Maia",
	"Menhet",
	"Merit",
	"Nebet",
	"Neferu",
	"Nit",
	"Nofret",
	"Nubemiunu",
	"Peseshet",
	"Rai",
	"Sadeh",
	"Sadek",
	"Sitamun",
	"Sitre",
	"Takhat",
	"Tarset",
	"Werenro",
	"Ahmose",
	"Amasis", "Amenemhet",
	"Anen", "Banefre",
	"Bek", "Henenu",
	"Huya", "Ibebi",
	"Idu",
	"Ineni", "Ipuki",
	"Irsu", "Kawad",
	"Kawab",
	"Kenamon", "Kewap", "Khafra", "Khuesebek",
	"Masaharta", "Meketre", "Merenre", "Metjen",
	"Nebamun", "Nehi",
	"Nekure", "Nessumontu",
	"Pawah", "Ramose", "Rudjek", "Sabaf", "Sebni",
	"Senusret", "Shabaka", "Somintu",
	"Thaneni", "Theti", "Aktas", "Anakis",
	"Armara", "Astaro",
	"Astaroz", "Azza", "Belez",
	"Bune", "Criella",
	"Damaia", "Ishte",
	"Jezebez",
	"Kali", "Kallista",
	"Kasdeya", "Lilith",
	"Makaria", "Markosian", "Nemeian", "Nija",
	"Oriana", "Osah", "Felaia", "Pura", "Pyra",
	"Rieta", "Sekhmet", "Semyaza",
	"Shava", "Zendaya",
	"Shax", "Vapula", "Vepar", "Verin",
	"Akmen", "Amon",
	"Astar", "Balam",
	"Bazin", "Cain",
	"Caim",
	"Cimer",
	"Damakos",
	"Euron",
	"Kairon",
	"Nicor",
	"Oriax",
	"Paymon",
	"Atraxas",
	"Samal",
	"Zamuz",
	"Valafar",
	"Zezan",

	"Carrion",

	"Ennui",

	"Ignominy",

	"Abrasax",
	"Ariatari",
	"Azizi",


	"Dawala",


	"Luzimer",


	"Nushim",





	"Solas",
	"Soleviel",
	"Soraz",



	"Umayma",



	"Balrog",
			"Sigar",
			'Azid',
			'Erenixir',
			"Aristofanes",
			"Daemon",
			"Negan",
			"Shadoxaw",
			"Shamsiel",
			"Shava",
			"Shax",
			"Shax",
			"Shedim",
			"Sinistrari",
			"Twisse",
			"Typhos",
			"Udal",
			"Udug",
			"Uetu",
			"Ukobach",
			"Umayma",
			"Vapula",
			"Vapula",
			"Kako",
			"Kakodaimon",
			"Kali",
			"Kali",
			"Kallista",
			"Kasdeya",
			"Kashto",
			"Kasmut",
			"Katana",
			"Kawab",
			"Kawad",
			"Kemanub",
			"Kenamon",
			"Kerberos",
			"Kesed",
			"Kesilim",
			"Kewap",
			"Kezer",
			"Khafra",
			"Khemed",
			"Khemut",
			"Khuesebek",
			"Solomon",
			"Solomon",
			"Solymo",
			"Somintu",

			"Vassago",
			"Venox",
			"Suriel",
			"Surin",
			"Vepar",
			"Vepar",
			"Verin",
			"Vexiana",
			"Terreur",
			"Thaneni",
			"Theti",
			"Tifarez",
			"Hutriel",
			"Ibebi",
			"Iblis",
			"Icosiel",
			"Idu",
			"Ipos",
			"Ipuet",
			"Ipuki",
			"Irsu",
			"Isacaron",
			"Ishte",
			"Itet",
			"Jendayi",
			"Jezebez",
			"Joba",
			"Joy",
			"Hauras",
			"Haurus",
			"Hawk",
			"Hecataea",
			"Hel",
			"Hellkin",
			"Helm",
			"Hemah",
			"Henenu",
			"Hentie",
			"Herit",
			"Heteferes",
			"Hexmorn",
			"Hod",

			"Hor",
			"Kababiel",
			"Kabiel",
			"Kairon",
			"Kokab",
			"Kokmah",
			'Bibiking',
			"Astar",
			"Astaro",
			"Daeva",
			"Daimon",
			"Dalkiel",
			"Damaia",
			"Damakos",
			"Dantanian",
			"Dante",
			"Dawala",

			"Astaro",
			"Veltis",
			"Venite",
			"Alloces",
			"Alp",
			"Amasis",
			"Amduscias",
			"Ameclo",
			"Astaroth",
			"Astaroth",
			"Astaroz",
			"Astaroz",
			"Astaroz",
			"At",
			"Atet",
			"Atraxas",
			"Azael",
			"Sitamun",
			"Sitre",
			"Sitri",
			"Skepter",
			"Skullrend",
			"Smen",
			"Solas",
			"Soleviel",
			"Kral",
			"Kunda",
			"Draconar",
			"Elberiz",
			"Eligor",
			"Emoniel",
			"Ennui",
			"Erinyes",
			"Faustus",
			"Felaia",
			"Felrend",
			"Flauros",
			"Foras",
			"Forneus",
			"Freddie",
			"Frenx",
			"Furcas",
			"Furfur",
			"Charogne",
			"Chax",
			"Buriel",
			"Cleopatra",
			"Clémence",
			"Coleman",
			"Coronzon",
			"Camion",
			"Camuel",

			"Decarabia",
			"Demoriel",
			"Dev",
			"Deva",
			"Dilan",
			"Doute",

			"Gilby",


			"Kurt",
			"Kurzam",
			"Labartu",
			"Lahmu",
			"Lamastu",

			"Lerajie",
			"Leviatan",
			"Leviatan",
			"Leviatan",

			"Lilith",
			"Lilivra",
			"Liliz",
			"Lodovico",
			"Lucifer",
			"Lucifer",


			"Lutin",
			"Luzer",
			"Luzimer",
			"Ma",
			"Macariel",
			"Madhorn",
			"Madilon",
			"Maia",
			"Makaria",
			"Malgaras",

			"Soraz",
			"Sorcaria",
			"Sulfuron",
			"Azazel",
			"Aziza",
			"Malkut",
			"Malpas",
			"Malphas",
			"Marbas",
			"Markosian",
			"Masaharta",
			"Maseriel",
			"Mastemoth",
			"Mayhem",
			"Mazakin",
			"Mazaquin",
			"Mazikin",
			"Mazzikin",
			"Mefistofeles",
			"Meketre",
			"Melody",
			"Menadiel",
			"Mend",
			"Menhet",
			"Merenre",
			"Metjen",

			"Moloch",
			"Moltenhorn",
			"Morax",
			"Mornara",
			"Mortigon",
			"Nenet",
			"Nephelin",
			"Nephilim",
			"Nessumontu",
			"Netzak",
			"Nicodemus",
			"Nicor",
			"Nighthowl",
			"Nofret",
			"Nourish",
			"Azizi","Raum",
			"Ravana",
			"Raventhorn",
			"Raysiel",
			"Reynolds",
			"Rhul",
			"Rieta",
			"Rimmon",
			"Risa",
			"Ritho",
			"Azza",
			"Baal",
			"Sabbat",
			"Azrael",
			"Sabnak",
			"Sadeh",
			"Sadek",
			"Sagrael",
			"Sahura",
			"Salem",
			"Saleos",
			"Samael",
			"Samal",
			"Sammael",
			"Sampson",
			"Carabia",
			"Carnesiel",
			"Carolin",
			"Carrion",
			"Caspiel",
			"Cassian",
			"Cawdrey",
			"Amorth",
			"Cerberus",
			"Cesmak",
			"Chagrin",
			"Chagrin",
			"Bael",
			"Bafomet",
			"Naberius",
			"Nebamun",
			"Lucifer",
			"Nebet",
			"Euron",
			"Eurynomus",
			"Neema",
			"Nefari",
			"Nefelin",
			"Neferu",
			"Nefilim",
			"Nehi",
			"Nekure",
			"Nemeian",
			"Baketamon",
			"Balam",
			"Balam",
			"Balberiz",
			"Uriel",
			"Uriel",
			"Usiel",
			"Ildrex",
			"Imp",
			"Incubus",
			"Indra",
			"Ineni",
			"Roneve",
			"Ronove",
			"Rudjek",
			"Sabaf",
			"Bubastis",
			"Buer",
			"Bulur",
			"Bune",
			"Bunefer",

			"Uziel",
			"Uzza",
			"Uzza",
			"Amenadiel",
			"Amenemhet",
			"Nub",
			"Nubemiunu",
			"Nushim",
			"Nuuch",
			"Nye",
			"Oary",
			"Onoskelis",
			"Onyxmaw",
			"Oriana",
			"Orias",
			"Oriax",
			"Orleans",
			"Ornias",
			"Ornias",
			"Orobas",
			"Osah",
			"Ose",
			"Otis",
			"Padiel",
			"Paimon",
			"Pairikas",
			"Pamersiel",
			"Pawah",
			"Paymon",
			"Pazuzu",
			"Peseshet",
			"Praredun",
			"Purson",
			"Rabisu",
			"Rai",
			"Ramla",
			"Ramose",

			"Amon",
			"Amon",

			"Valac",
			"Valafar",
			"Valefor",
			"Wry",
			"Vornak",
			"Vorrela",
			"Werenro",
			"Xonsu",
			"Yesod",
			"Gamalxipoz",
			"Raggadragga",
			"Adramalek",
			"Abdamelek",
			"Abezetibou",        "Amunet",
			"Amynus",
			"Anakis",
			"Andra",
			"Andras",
			"Andrealfus",
			"Andromalius",
			"Aneksi",
			"Anen",
			"Angra",
			"Antaura",
			"Antichrist",
			"Antichristian",
			"Apocalypse",
			"Apolion",
			"Apronadius",
			"Ariatari",
			"Ariman",
			"Armadiel",
			"Armara",

			"Abigor",
			"Ablo",
			"Temerity",
			"Temperance",
			"Temple",
			"Tenacious",
			"Abrasax",
			"Abraxas",
			"Abraxis",
			"Asmodeus",
			"Azamut",
			"Azhemut",
			"Behmut",        "Aseliel",
			"Bofi",
			"Bolfri",
			"Boston",
			"Botis",

			"Behemut",        "Busyasta",
			"Cabariel",
			"Caim",
			"Caim",
			"Cain",

			"Scox",
			"Gusion",
			"Hades",
			"Hagenti",
			"Haine",
			"Halahel",
			"Halpas",
			"Harlequin",
			"Harris",
			"Hasard",

			"Sebni",
			"Sefirot",
			"Sekhmet",
			"Semyaza",
			"Senusret",
			"Separ",
			"Sephirot",
			"Sept",
			"Serafina",
			"Serene",
			"Sethenes",
			"Shabaka",
			"Shadeveil",

			"Cunning",
			"Lumin",
			"Mirth",
			"Abuse",
			"Abyss",
			"Abyx",
			"Acaos",
			"Aeon",
			"Aeshma",
			"Sarakiel",
			"Sarapous",
			"Sariel",
			"Saroy",
			"Satan",
			"Satanael",

			"Aexma",
			"Agares",
			"Agato",
			"Agatodaimon",
			"Sydonay",
			"Symiel",
			"Taint",
			"Takhat",
			"Tarset",
			"Taru",
			"Tase",
			"Tauret",
			"Teofilus",
			"Agraz",
			"Nija",
			"Nisroc",
			"Nit",
			"Ahmose",
			"Ahset",
			"Ainin",
			"Akmen",
			"Aktas",
			"Zaffis",
			"Zamuz",
			"Zarika",
			"Zeal",
			"Zendaya",
			"Zenglac",
			"Zepar",
			"Zephyron",
			"Zerakiel",
			"Zesiro",
			"Zeu",
			"Zezan",
			"Zohak",
			"Zohk",
			"Zorlarg",
			"Zoroastra",
			"Gabriele",
			"Gadreel",
			"Gadreel",
			"Gadriel",
			"Gamaliel",
			"Gamigin",
			"Garacriel",
			"Geburah",
			"Gediel",
			"Gemori",
			"Ashmedai",
			"Asmodeus",
			"Asmodius",
			"Banefre",
			"Baphomet",
			"Barbatos",
			"Barbiel",
			"Barbuel",
			"Barmiel",
			"Baruchas",
			"Bathin",
			"Bazin",
			"Beal",
			"Beelxebub",
			"Behemoth",
			"Beherit",
			"Bek",
			"Belet",
			"Belez",
			"Belfegor",
			"Belial",
			"Beliar",
			"Belzebub",
			"Beriz",
			"Bernael",
			"Bidiel",
			"Bidiel",
			"Bifrons",
			"Bilet",
			"Binah",


		]

	Names = []
	Names += Virtue_Names
	if TIEFLING:
		return Names

	Names += Fiend_Names


	Names += [
		'Hashut',
		'Nurgle',
		'Lanesh',
		'Tizench',
		'Korne',
		'Djall',
		'Diablo',
		'Akuma',
		'Mahhemut',
		'Irdlirvirisissong',
		'Mion',
		'Oni',
		'Renma',
		'Akuma',
		'Amura',
		'Mahem',
		]

	if MALE:
		Names += [
		'Warlock',
		'Tlacatecolotle',
		'Siglorel',
		'Peckol',
		'Nickel',
		'Etsai',
		'Drakul',
		'Stolas',
		'Onigumo',
		'Keshava',
		'Ifearnán',
		'Asmodeus',
		'Algol',
		]

	if FEMALE:
		Names += [
		'Minetta',
		'Vitani',
		'Kishimojin',
		'Jeryline',
		'Gello',
		'Cuauhtzitzimitle',
		'Badbi',
		'Asmodina',
		'Arle',
		'Ahez',
		'Yurena',
		'Guinevere',
		'Morrigan',
		'Dante',
		'Faust',
		'Faustus',
		]

	return Names

def Surnames(Type):
	Surnames = [""]
	return Surnames

def Phonotactic(Type):
	onset  = [""]
	nuclei = [""]
	codas  = [""]
	onset += [
		'Nix','Shal','Beh','Az','Un','Mah',
		'El']
	nuclei += [
		'','ar','e','ez','iz','eyal','eh',
		'az','er','ad', 'em', 'id', 'of',
		'elz',	 ]
	codas += [
		'ire','ow','ut','el','ik','i']


	return onset, nuclei, codas

def Surphonotactic(Type):
	onset  = [""]
	nuclei = [""]
	codas  = [""]
	return onset, nuclei, codas
