'''
Names for Giants
Inspirations
	- Giants (Meaning)
	Wairimu (f)  Ōga (m)
'''

def Names(Type):
	MALE    = "He"    in Type
	FEMALE  = "She"   in Type
	AGENDER = "They"  in Type

	SUBTYPE = "Subtype" in Type
	ONI = "Oni" in Type

	Names = [
	# A
		"Ambersad",		"Ambrosius",	"Artor", 	"Avalon",		"Arzur",		"Andun",				"Andurd",				"Aureliu",				"Agrippa",				"Ananias",				"Armin",				"Atlas",				"Atlumun",				"Atlaria",				"Aurelien",				"Antonialot",				"Aeliana",				"Augustu",				"Aquila",				"Artorius",				"Acianus",				'Anerdothis',				"Ambershade",	"Arthur",		"Artorius",		"Avalonia",		 		"Ambrosius",				"Aureliot",				"Antonia",	"Atlas",	"Atlar", 	"Adrianne", 		"Agravainu",		"Asinino",		'Admalivar',		"Arturus",		"Aurelius",		"Agrippa",		"Ananias",		"Atlas",		"Atlumun",		"Atlaria",
	# B
		"Bunce",	"Bridget",	"Bunari",	"Bundero",	"Brasan",	"Bunasas",
	# C
		"Carroll",	"Cadet",	"Calamundis",	"Colozus", "Colozu",	"Colossu",	"Casade",	"Coeus",	"Crius",	"Caramu",	"Calan",	"Cronus",
	# D
		"Droroc",	"Darwin",	"Darvin",	"Xarles",
	# F
		"Flasari",	"Foebe",
	# G
		"Geroro",	"Gerdur",	"Grad",
	# H
		"Hiperion", "Haiperion", "Heuperion",
	# I
		"Iritar", "Iapetus",
	# L
		"Lewis",
	# M
		"Memosin",
	# R
		"Rehar",
	# T
		"Tialam",	"Tezis",		"Tecis",	"Tethis",	"Themis",	"Thea",










		"Bundun",		"Andurd",		"Draro",		"Tisar",		"Coni",		"Bunfunfu",		"Bundunde", "Candu", "Teri",		"Casaris", "Candun", "Andun",		"Caris", "Bunasa", "Tialas",		"Brisar", "Bumo", "Bunde",		"Ragnarok", "Arzur", "Arturus",		"Bedivere", "Bedwyr", "Bohort",		"Bors", "Cai", "Caradoc",		"Caradog", "Culch", "Elaine",		"Enid", "Enide", "Gaheriet",		"Gaheris", "Galaad", "Galahad",		"Gareth", "Garez", "Gauvain",		"Goven", "Gawain",		"Geraint",		"Gualguainu",		"Guendolen",		"Guendolena",		"Guenevere", "Guinivere",		"Guiomar", "GynezGyneth",		"Hector", "Hoel", "Igerna",		"Igraine", "Iseult", "Iseut",		"Isolda", "Isolde", "Kay",		"Lancelot", "Loncelote",		"Lancelote", "Laudine", "Linet",		"Lionel", "Lionesse", "Lionors",		"Lohengrin",		"Loherangrin", "Lot", "Luned",		"Lunete", "Lynet", "Lynette",		"Lyones", "Lyonesse",		"Lyonors", "Medraut", "Medrod",		"Mordred", "MerlinMyrdin",		"Merlinus", "Merdinus",		"Modred", "Mordred", "Morgaine",		"Morgen", "Nimue", "Vivien",		"Niniane", "Olwen",		"Owain", "Parsifal", "Parzival",		"Percival", "Pellam", "Pelleas",		"Pellejand",		"Pellejan",		"Pelles", "Beli", "Pellinore",		"Percival", "Peredur", "Tristan",		"Drust", "Drustan", "Urien",		"Uther", "Uthyr", "Walganus",
		"Yiseut", "Iseult", "Yisolt",
		"Iseult", "Yivain", "Owain", "Yiwain",
		"Lynn",
		"Lunete",
		"Eluned",
		"Lojengrin", "Lorraine", "Lot",
		"Gaius", "Iseult", "Gawain", "Garez",
		"Enid", "Helen", "Caratacos",
		"Caradog", "Bors", "Bedivere",
		"Tigsar", "Morgan", "Arthur",
		"Oceanus",
		"Branwen", "Caledor",
		"Dagonet",
		"Ectoriu",
		"Elainea",
		"Fionor",
		"Galaz",
		"Guerrier", "Hengist", "Igrainia",
		"Jernon", "Kaledvoulc", "Llynis",
		"Mabonagrain", "Niviene", "Orkney",
		"Pelinora",
		"Questar", "Rhience",
		"Segwarides",
		"Tintagil", "Urian",
		"Vortigern",
		"Yigerne",
		"Zephyros",

		"Blaiddyd",
		"Caliburnu",
		"Duirward",
		"Elthain",
		"Galajault",
		"Hiberna",
		"Isoude",
		"Julanar",
		"Kelpius",
		"Lucanor",
		"Meliodas",
		"Nimuena",
		"Olyndicus",
		"Pellamor",
		"Querent",
		"Rowenar",
		"Siluria",
		"Tristanus",
		"Ulfius",
		"Vivienus",
		"Yisbaden",
		"Argante",
		"Brocéliande",
		"Corbenic",
		"Dinadan",
		"Evrain",
		"Guiber",
		"Hoelus",
		"Ider",
		"Joyous",
		"Kerwyn",
		"Lynettea",
		"Moire",
		"Niniane",
		"Oberon",
		"Pendragon",
		"Questine",
		"Roncesvalles",
		"Seraphiel",
		"Tegid",
		"Utherius",
		"Vortimer",
		"Ywaineth",
		"Zephyrius",

		"Bronwen",
		"Caerleon",
		"Dindrane",
		"Elyan",
		"Galeran",
		"Harlequin",
		"Isolier",
		"Jaufré",
		"Kynereth",
		"Lyones",
		"Morgause",


		"Ossian",

		"Palamedes",

		"Quex",


		"Sadb",

		"Taulurd",

		"Uriens",


		"Yisbail",

		"Cassius",
		"Drusus",
		"Flavia",
		"Gaius",
		"Hadrian",
		"Julia",
		"Lucretia",
		"Maximu",
		"Octavia",
		"Priscus",
		"Romulus",
		"Sabina",
		"Tacitu",

		"Brutu",
		"Cornelia",
		"Decimu",
		"Faustina",
		"Gracchu",
		"Horatia",
		"Livia",
		"Marcellu",
		"Nerva",
		"Pontius",
		"Quintus",
		"Regulus",
		"Sergius",
		"Tiberius",

		"Antonia",
		"Claudius",
		"Diana",
		"Felix",
		"Germanicus",
		"Helena",
		"Juno",
		"Lucius",
		"Minerva",
		"Octavian",
		"Portia",
		"Remus",
		"Scipio",
		"Titus",

		"Balbus",
		"Cicero",
		"Draco",
		"Fabius",
		"Galba",
		"Hercules",
		"Julius",
		"Lucretius",
		"Martialis",
		"Nero",
		"Paulinus",
		"Rufus",
		"Seneca",
		"Merlina",
		"Gaiadoc",
		"Lancelian",
		"Guinerva",
		"Aureliot",

		"Galahadrian",
		"Octarthur",
		"Elynia",
		"Cassilote",
		"Drustus",
		"Helenaire",
		"Guainu",
		"Titania",
		"Brutigern",
		"Flaviad",
		"Luciuslyn",
		"Marcian",
		"Nimoria",
		"Guenu",
		"Viviane",
		"Tristianu",
		"Agravainu",
		"Maximor",
		"Bellereu",
		"Morgausea",
		"Lancelotu",
		"Priscival",
		"Romelein",
		"Sabinael",
		"Taciturn",

		"Bedwiru",
		"Caratacu",
		"Dianadoc",
		"Faustelot",
		"Gwenyivaru",
		"Herculot",
		"Lunetea",
		"Octaviane",
		"Pontifex",
		"Quintavere",
		"Regulad",
		"Senegalad",
		"Tituriu",

		"Caiulu",
		"Drusin",
		"Felixor",
		"Germanica",
		"Horatine",
		"Luneliu",
		"Minervadoc",
		"Balbusu",   # from 'balbus', meaning stammering or inarticulate
		"Clunclu",   # a twist on 'cluncus', a nonsense word mimicking 'clumsy'
		"Nugaxiu",   # from 'nugax', meaning trivial or petty
		"Lirpalo",   # from 'lirpa', a playful twist on a nonexistent Latin word
		"Brutulu",   # a play on 'brutus', meaning heavy, dull, or stupid
		"Pedicu",    # sounds like a Latin word but is actually nonsensical, implying something foot-related
		"Flatulu",   # humorous twist on 'flatus', meaning blowing or a gust
		"Stultor",   # from 'stultus', meaning foolish
		"Asinino",   # from 'asininus', pertaining to a donkey, or foolish
		"Confusio",  # from 'confusio', meaning confusion
		"Caudex",    # literally a block of wood, used to mean blockhead
		"Caputus",   # play on 'caput', head, implying a 'big head'
		"Mogonus",   # a made-up word that sounds like a Latin name but is just silly
		"Semicapru", # 'half-goat', nonsensical and humorous
		"Ineptor",   # from 'ineptus', meaning inappropriate or silly
		"Somniculo", # a playful take on 'somniculus', little sleeper
		"Naso",      # meaning nose, implying someone with a big nose
		"Bovido",    # from 'bovidus', ox-like, implying slow-witted
		"Tardigradu",   # slow stepper, a play on the term 'tardigrade'
		"Bumbulu",
		"Blunderu",
		"Lorariu",
		"Nonplusiu",
		"Gurguliu",
		"Snoru",
		"Cacofonix",    # from 'cacophony', implying a loud, dissonant noise

		"Glutu",        # a twist on 'glutus', giving the impression of gluttony

		"Aurelien",
		"Antonialot",
		"Aeliana",
		"Augustu",
		"Aquila",
		"Artorius",

		"Bacchu",

		"Camilla",
		"Cato",
		"Claudiad",

		"Domitian",
		"Dido",
		"Domicia",


		"Fauna",
		"Florian",
		"Florianel",
		"Flunfum",

		"Gratian",
		"Gordian",
		"Galainu",

		"Hadriana",
		"Honori",
		"Honoriu",
		"Helenor",

		"Igrainiu",

		"Jovian",
		"Jadriana",
		"Jonoriu",
		"Julianor",
		"Jelenor",
		"Juniu",

		"Lin",
		"Linu",
		"Laris",
		"Lariu",
		"Lucion",
		"Ludicro",
		"Ludicru",

		"Mercuriu",
		"Mars",
		"Marcelot",

		"Numa",
		"Nentres",

		"Ovid",
		"Octaviad",
		"Oblivio",

		"Proserpina",
		"Plini",
		"Pliniu",
		"Percivu",
		"Porcia",

		"Quirinus",

		"Rea",
		"Rotder",
		"Rience",
		"Remulu",

		"Saturn",
		"Sever",
		"Scipiogern",

		"Tull",
		"Trajan",
		"Titan",
		"Tibergain",

		"Vergil",
		"Vitell",
		"Vespasia",
		"Vestia",
		"Vulcan",
		"Varliniu",
		"Vesta",
		"Vortigan","Vacu",     "Vespaval","Valkiriu","Vivianu","Vespasian","Varinia","Valeriu",
		"Vitu",




	# B
		"Beli",
		"Bunde",
		"Bumo",
		"Brisar",
		"Bors",
		"Bohort",
		"Bedwyr",
		"Bedivere",
		"Bunasa",
		"Bundunde",
		"Bunfunfu",
		"Bundun",
		"Behemoth",
		"Bunce",
		"Bridget",
		"Bunari",
		"Bunasas",
		"Brasan",
		"Bundero",
		"Bedivere",
		"Bors",
		"Bacchu",
		"Balbusu",
		"Bedwiru",
		"Bellereu",
		"Blunderu",
		"Bovido",
		"Brutulu",
		"Bumbulu",
		"Bronhor",
	# C
		"Cadet",
		"Caramu",
		"Culch",
		"Caradog",
		"Caradoc",
		"Cai",
		"Caris",
		"Candun",
		"Casaris",
		"Candu",
		"Coni",
		"Calamundis",
		"Colossu",
		"Casade",
		"Cous",
		"Criu",
		"Cronu",
		"Calan",
		"Caradog",
		"Caratacos",
		"Caliburnu",
	# D
		"Draro",
		"Droroc",
		"Drust",
		"Drustan",
	# E
		'Endether',
		"Edenac",
		"Enide",
		"Enid",
		"Elaine",
		"Eren",
		'Evixer',
		"Erculis",
		"Erculies",
	# F
		"Flasari",
		"Frigga",
		"Foebe",
		"Fauna",
		"Florian",
		"Florianel",
		"Flunfum",
	# G
		"Gaheriet",
		"Gaheris",
		"Galaad",
		"Galahad",
		"Gareth",
		"Garez",
		"Gauvain",
		"Goven",
		"Gawain",
		"Geraint",
		"Gualguainu",
		"Guendolen",
		"Guendolena",
		"Guenevere",
		"Guinivere",
		"Guiomar",
		"Gynez",
		"Gyneth",
		"Geroro",
		"Gerdur",
		"Grad",
		"Gorm",
	# H
		'Horumis',
		"Hector",
		"Hoel",
		"Hyperion",
	# I
		'Irezey',
		'Ipleya',
		"Igerna",
		"Iapetu",
		"Igraine",
		"Iseult",
		"Iseut",
		"Isolda",
		"Isolde",
		"Kai",
		"Kay",
	# L
		"Lancelot",
		'Laon',
		"Lancelote",
		"Laudine",
		"Linet",
		"Lionel",
		"Lionesse",
		"Lionors",
		"Lohengrin",
		"Loherangrin",
		"Loncelote",
		"Lot",
		"Luned",
		"Lunete",
		"Lynet",
		"Linette",
		"Liones",
		"Lionesse",
		"Lionors",
		'Livarjon'
	# M
		"Medraut",
		"Medrod",
		"Memosyne",
		"Merdinus",
		"Maximor",
		"Minervadoc",
		"Mogonus",
		"Morgauser",
	# O
		'Odaxi',
		'Ofon',
	# R
		'Ragmarok',
	# V
		'Valief',
	# W
		"Wiris",
		"Walgax",

		"Eluned",
		"Enid",
		"Gaius",
		"Garez",
		"Gawain",
		"Helen",
		"Iseult",
		"Isult",
		"Iseult",
		"Lojengrin",
		"Lorraine",
		"Lot",
		"Lunete",
		"Lynn",
		"Merlin",
		"Merlinus",
		"Micasa",
		"Mikasa",
		"Modred",
		"Mordred",
		"Mordred",
		"Morgaine",
		"Morgan",
		"Morgen",
		"Myrdin",
		"Nimue",
		"Niniane",
		"Olwen",
		"Owain",
		"Owain",
		"Parsifal",
		"Parzival",
		"Pellam",
		"Pelleas",
		"Pellejan",
		"Pellejand",
		"Pelles",
		"Pellinore",
		"Percival",
		"Percival",
		"Peredur",
		"Ragnarok",
		"Rhea",
		"Teri",
		"Tethis",
		"Tethys",
		"Tezis",
		"Thea",
		"Themis",
		"Tialam",
		"Tialas",
		"Tigsar",
		"Tisar",
		"Tristan",
		"Urien",
		"Uther",
		"Uthyr",
		"Vivien",
		"Walganus",
		"Yiseut",
		"Yisolt",
		"Yivain",
		"Yiwain",
		"Branwen",
		"Caledor",
		"Dagonet",
		"Ectoriu",
		"Elainea",
		"Fionor",
		"Galaz",
		"Guerrier",
		"Hengist",
		"Igrainia",
		"Jernon",
		"Kaledvoulc",
		"Llynis",
		"Mabonagrain",
		"Niviene",
		"Orkney",
		"Pelinora",
		"Questar",
		"Rhience",
		"Segwarides",
		"Tintagil",
		"Urian",
		"Vortigern",
		"Yigerne",

		"Oceanus",
		"Blaiddyd",
		"Duirward",
		"Elthain",
		"Galajault",
		"Hiberna",
		"Isoude",
		"Julanar",
		"Kelpius",
		"Lucanor",
		"Meliodas",
		"Nimuena",
		"Olyndicus",
		"Pellamor",
		"Querent",
		"Rowenar",
		"Siluria",
		"Tristanus",
		"Ulfius",
		"Vivienus",
		"Yisbaden",
		"Argante",
		"Brocéliande",
		"Bronwen",
		"Brutu",
		"Caerleon",
		"Cassius",
		"Corbenic",
		"Cornelia",
		"Decimu",
		"Dinadan",
		"Dindrane",
		"Drusus",
		"Elyan",
		"Evrain",
		"Faustina",
		"Flavia",
		"Gaius",
		"Galeran",
		"Guiber",
		"Hadrian",
		"Harlequin",
		"Hoelus",
		"Ider",
		"Isolier",
		"Jaufré",
		"Joyous",
		"Julia",
		"Kerwyn",
		"Kynereth",
		"Lucretia",
		"Lynettea",
		"Lyones",
		"Maximu",
		"Moire",
		"Morgause",
		"Niniane",
		"Oberon",
		"Octavia",
		"Ossian",
		"Palamedes",
		"Pendragon",
		"Priscus",
		"Questine",
		"Quex",
		"Romulus",
		"Roncesvalles",
		"Sabina",
		"Sadb",
		"Seraphiel",
		"Tacitu",
		"Taulurd",
		"Tegid",
		"Uriens",
		"Utherius",
		"Valeriu",
		"Vitu",
		"Vortimer",
		"Yisbail",
		"Ywaineth",

		"Gracchu",
		"Horatia",
		"Livia",
		"Marcellu",
		"Nerva",
		"Pontius",
		"Quintus",
		"Regulus",
		"Sergius",
		"Tiberius",
		"Varinia",
		"Claudius",
		"Diana",
		"Felix",
		"Germanicus",
		"Helena",
		"Juno",
		"Lucius",
		"Minerva",
		"Octavian",
		"Portia",
		"Remus",
		"Scipio",
		"Titus",
		"Vespasian",
		"Balbus",
		"Cicero",
		"Draco",
		"Fabius",
		"Galba",
		"Hercules",
		"Julius",
		"Lucretius",
		"Martialis",
		"Nero",
		"Paulinus",
		"Rufus",
		"Seneca",
		"Merlina",
		"Gaiadoc",
		"Lancelian",
		"Guinerva",
		"Vivianu",
		"Galahadrian",
		"Octarthur",
		"Elynia",
		"Cassilote",
		"Drustus",
		"Helenaire",
		"Guainu",
		"Titania",
		"Brutigern",
		"Flaviad",
		"Luciuslyn",
		"Marcian",
		"Nimoria",
		"Guenu",
		"Cacofonix",
		"Caiulu",
		"Camilla",
		"Caputus",
		"Caratacu",
		"Cato",
		"Caudex",
		"Claudiad",
		"Clunclu",
		"Confusio",
		"Dianadoc",
		"Domitian",
		"Drusin",
		"Faustelot",
		"Felixor",
		"Flatulu",
		"Germanica",
		"Glutu",
		"Gurguliu",
		"Gwenyivaru",
		"Herculot",
		"Horatine",
		"Ineptor",
		"Lancelotu",
		"Lirpalo",
		"Lorariu",
		"Luneliu",
		"Lunetea",
		"Naso",
		"Nonplusiu",
		"Nugaxiu",
		"Octaviane",
		"Pedicu",
		"Pontifex",
		"Priscival",
		"Quintavere",
		"Regulad",
		"Romelein",
		"Sabinael",
		"Semicapru",
		"Senegalad",
		"Snoru",
		"Somniculo",
		"Stultor",
		"Taciturn",
		"Tardigradu",
		"Tituriu",
		"Tristianu",
		"Vacu",
		"Valkyriu",
		"Vespaval",
		"Viviane",
		"Dido",
		"Domicia",
		"Igrainiu",
		"Jadriana",
		"Jelenor",
		"Galainu",
		"Gordian",
		"Gratian",
		"Hadriana",
		"Helenor",
		"Honori",
		"Honoriu",
		"Jonoriu",
		"Jovian",
		"Julianor",
		"Juniu",
		"Laris",
		"Lariu",
		"Lin",
		"Linu",
		"Lucion",
		"Ludicro",
		"Ludicru",
		"Marcelot",
		"Mars",
		"Mercuriu",
		"Nentres",
		"Numa",
		"Oblivio",
		"Octaviad",
		"Ovid",
		"Percivu",
		"Plini",
		"Poliniu",
		"Porcian",
		"Proserpina",
		"Quirinus",
		"Rea",
		"Remulu",
		"Rience",
		"Rotder",
		"Saturn",
		"Scipiogern",
		"Sever",
		"Tibergain",
		"Titan",
		"Trajan",
		"Tull",
		"Varliniu",
		"Vergil",
		"Vespasia",
		"Vesta",
		"Vestia",
		"Vitell",
		"Vortigan",
		"Vulcan",
	# Z
		"Zilchais", "Zepfirus","Zefiros", "Zilchais","Zephyrius",

		]

	if  ONI:
		Names += [
		  "Ugawai",
		  "Wasabi",
		  "Kintsugi",
		  "Wabisabi",
			]
	return Names

def Surnames(Type):
	return Names(Type)

def Phonotactic(Type):
	onset  = [""]
	nuclei = [""]
	codas  = [""]
	onset +=  [
	"Aur", "Agr", "Ant", "Atil", "Al", "Ar", "As", "Ac", "Am",
	"Bron", "Bur", "Bac", "Ben", "Bor", "Blas", "Bimb", "Bey", "Berg", "Bins",
	"Cax", "Cork", "Cruf", "Curt", "Cel", "Cind", "Clet", "Carl", "Chom", "Cub", "Chon", "Choms",
	"Dor", "Drun", "Dax", "Dix", "Dex", "Dux", "Dalm", "Dolm", "Dilm",
	"El", "En", "Ed", "Eg", "Er", "Es", "Et", "Eurt", "Ev", "Eirt",
	"Fart", "Flep", "Fenr", "Fonr", "Funr", "Fanr", "Fin", "Fomt",
	"Gamt", "Gomt", "Gumt", "Gem", "Gam", "Grimt", "Gig", "Galg",
	"Henr", "Honr", "Hanr", "Hunr", "Hidr", "Hedr", "Hodr", "Hadr","Hel",
	"In", "Ig", "Is", "Id", "Iol", "Iv", "Il", "Im",
	"Jurd", "Jord", "Jard", "Jerd", "Jot", "Jut", "Jit", "Jot",
	"Kat", "Ket", "Kit", "Kot", "Kut", "Kap", "Knox", "Krix",
	"Lix", "Lox", "Lax", "Lex", "Lux", "Laix", "Laex", "Liox",
	"Max", "Mix", "Mex", "Mox", "Mux", "Mac", "Mec", "Mic",
	"Nox", "Nex", "Nix", "Noc", "Nux", "Nec", "Nax", "Nic",
	"Oc", "Or", "Os", "Ov", "Ol", "Od", "Oc", "Op",
	"Perx", "Porx", "Parx", "Pirx", "Purx", "Perc", "Pronx", "Pox",
	"Quin", "Quix", "Quen", "Quex", "Quinx", "Quenx", "Ques", "Quis",
	"Rex", "Rox", "Rax", "Rix", "Rux", "Ren", "Ron", "Ran",
	"Sax", "Sex", "Six", "Sox", "Sux", "San", "Scat", "Stoc",
	"Tir", "Trav", "Tav", "Torv", "Turc", "Tirv", "Thom", "Tem",
	"Van", "Ven", "Vin", "Von", "Vun", "Val", "Vil", "Vel",
	"Zic", "Zox", "Zux", "Zex", "Zax", "Zoc", "Zix", "Zec"]
	nuclei += [
		"an", "alen", "ains", "arak", "asix",
				"ex", "exan", "enax", "ein",
				'en',		"eox", "eoc",
				"il", "ican", "ient", "ilit", "ion", "ian",  "ixan",
				"ilox", "ixal", "ilex", "ixul",
				"on", "oux", "orac",
				"uz", "una",
				"uxar", "urix",]
	codas +=  ["u", "ix", "as", "is", "or", "un", "ia", "u", "al", "ar",
					   "um", "an", "in", "el", "on", "en", "er", "ar",
					   "ad", "or", "ia", "ic", "os", "id", "ot", "ul", "ud",
					   "or", "an", "ur", "en", "on", "al", "ir", "ia", "es",
					   "ar", "et", "ia", "or", "or", "ia", "us", "in", "al",
					   "or", "er", "en", "is", "an", "u", "ic", "u", "in",
					   "u", "an", "er", "u", "ad", "os", "es", "an", "or"]
	return onset, nuclei, codas

def Surphonotactic(Type):
	return Phonotactic(Type)
