			("Soldier", "Renowned as the {best} {heroic_class} of {hometown}, {full_name} is also the city's best hope for ridding it of the {faction}. Even though {name} wields a unique {magic_weapon}, {name}'s most powerful weapon is {SuperiorSkill}."),
			("Druid", "As a warden of the wilds, {hero} channels the {natural_virtue} of the living world, seeking harmony so that all life may flourish amidst nature's untamed will."),

			("Noble",	"{name} guides and protects {hometown}, as a symbol of hope, and a portent of great change. "),
			("Fighter", 	"Once forced into the brutal life of a gladiator, {name} survived by pure discipline. Now, free from the chains of former masters, {name} fights for the downtrodden and disadvantaged, wielding the {weapon} of the arena with unmatched skill and a strategist's mind. "),
			("Barbarian",	"Though {name} was enslaved and thrown into the gladiator's pit, it was a wild, unbreakable will and primal fury that kept {name} from ever truly being a slave. Now, unleashed, {name} fights for the downtrodden and disadvantaged, rage as much a weapon as the {weapon} of the gladiator. "),
			("",	"Abandoning the {faction} and adopting the title of {hero}, {name} now strikes alone, ready to be the deadly weapon the {kingdom} needs. "),
			("",	"Innately connected to the magic of the {magic_realm}, {name} is a young {species} who {MagicPower}. "),
			("",	"Now {hero} seeks not glory, but meaning. Their story is just beginning. "),
			("",	"Once a simple {background}, {name} is now traveling the world as {hero}, a well known {heroic_class}. {name} is now in search of remnants of the {Ancestors}. "),
			("",	"{Learner}"),
			#("",	"{FrontierWarden}"),
			#("Soldier",	"{ReluctantSoldier}"),
			#(("Chaotic", "Soldier"),	"{RevolutionarySoldier}"),
			#("Warlock",	"{CursedBearer}"),
			#("Elf",	"{SpiritWanderer}"),
			#("Rogue", "{ExAssassin}"),
			#("Barbarian", "{GladiatorFreedman}"),
			#("Fighter", "{GladiatorFreedman}"),
			#("Paladin", "{GladiatorFreedman}"),
			#("Noble", "{KingdomGuardian}"),
			#("Noble", "{BetrayedHeir}"),
			#("", "{ChosenByProphecy}"),
			#("", "{Redempter}"),
			#("", "{Searcher}"),
			],
		"godlike_entity":[
			("", "Elder Dragon"),
			("", "Primordial Titan"),
			("", "World Serpent"),
			("", "Starforger"),
			("", "Celestial Phoenix"),